[workspace]
members = []

[package]
name = "semblance_rust"
authors = ["cyrex562"]
version = "0.0.1"
publish = false
edition = "2018"
autobins = false

[lib]
name = "semblance_rust"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]


[dependencies]
c2rust-bitfields = "0.3"
libc = "0.2"



