// OUTPOST_0015.c
// Generated by decompiling OUTPOST.EXE
// using Reko decompiler version 0.9.2.3.

#include "OUTPOST_0015.h"

// 0015:0052: Register word16 fn0015_0052(Register (memptr (ptr16 Eq_18) Eq_14) bx, Register out ptr16 dxOut, Register out ptr16 siOut)
// Called from:
//      fn0015_05E2
word16 fn0015_0052(struct Eq_14 Eq_18::* bx, ptr16 & dxOut, ptr16 & siOut)
{
	Eq_17 ax_17 = (ds->*bx).t001E;
	ui16 dx_18 = (ds->*bx).w0020;
	uint16 wLoc08_143 = 0x00;
	do
	{
		ptr16 Eq_63::* sp_106;
		struct Eq_39 Eq_18::* ax_29 = (ds->*bx).a0000[wLoc08_143];
		struct Eq_39 Eq_18::* wLoc0A_146 = ax_29;
		if (ax_29 != &Eq_18::t0000 && wLoc08_143 != 0x03)
		{
			struct Eq_39 Eq_18::* wLoc0E_147 = &Eq_18::t0000;
			do
			{
				struct Eq_39 Eq_18::* ax_43 = (ds->*wLoc0A_146).ptr0004;
				struct Eq_95 * es_bx_45 = (ds->*wLoc0A_146).ptr0008;
				struct Eq_39 Eq_18::* wLoc0C_149 = ax_43;
				struct Eq_49 * es_46 = SLICE(es_bx_45, selector, 16);
				if (es_bx_45->w000A == 0x00)
				{
					sp_106 = fp - 24;
					if (fn0015_0510(es_46, 0x01) == 0x00)
						goto l0015_00F9;
					if (ax_43 == wLoc0A_146)
						wLoc0C_149 = &Eq_18::t0000;
				}
				else if (wLoc0E_147 == &Eq_18::t0000)
					wLoc0E_147 = wLoc0A_146;
				wLoc0A_146 = wLoc0C_149;
			} while (wLoc0C_149 != wLoc0E_147);
		}
		uint16 v16_91 = wLoc08_143 + 0x01;
		sp_106 = fp - 24;
		wLoc08_143 = v16_91;
	} while (v16_91 < 0x05);
	if ((ds->*bx).ptr0032 != &Eq_2::t0000)
	{
		<anonymous> Eq_2::* ax_100 = (ds->*bx).ptr0032;
		(0015->*ax_100)();
	}
l0015_00F9:
	ui32 dx_ax_137 = SEQ(dx_18, ax_17) - (ds->*bx).t001E;
	ptr16 si_132 = ss->*sp_106;
	dxOut = SLICE(dx_ax_137, word16, 16);
	siOut = si_132;
	return (word16) dx_ax_137;
}

// 0015:010C: void fn0015_010C(Stack uint16 wArg04, Stack uint16 wArg06, Stack Eq_107 wArg08, Stack Eq_108 ptrArg0A)
// Called from:
//      fn0015_1902
void fn0015_010C(uint16 wArg04, uint16 wArg06, Eq_107 wArg08, Eq_108 ptrArg0A)
{
	Eq_107 psegArg0C_156 = SLICE(ptrArg0A, selector, 16);
	Eq_107 wLoc0E_151;
	Eq_107 wLoc0A_149;
	Eq_108 wLoc0C_150;
	Eq_107 wLoc06_144 = 0x00;
	uint16 wLoc08_145 = 0x00;
	Eq_107 es_14 = SLICE(ptrArg0A, selector, 16);
	Eq_108 bx_15 = (word16) ptrArg0A;
	if (*((word32) ptrArg0A + 20) == 48813)
	{
		Eq_108 wLoc04_148;
		ds->w5F30 = 0x01;
		if (wArg04 != 0x01)
		{
			if (wArg04 != 0x02)
			{
				if (wArg04 != 0x04)
					return;
				wLoc04_148.u0 = 0x00;
			}
			else
				wLoc04_148.u0 = 0x02;
		}
		else
		{
			wLoc04_148.u0 = 0x01;
			if (*((word32) ptrArg0A + 24) == 0x00)
			{
				wLoc0A_149 = es_14;
				wLoc0C_150 = bx_15;
				wLoc0E_151.u0 = 0x04;
l0015_0127:
				word16 cx_256;
				word16 di_257;
				fn0015_1E61(wLoc0E_151, wLoc0C_150, wLoc0A_149, out cx_256, out di_257);
				return;
			}
		}
		Eq_107 ds_48 = psegArg0C_156;
		while (wLoc06_144 <= wArg08 && (wLoc06_144 < wArg08 || wLoc08_145 < wArg06))
		{
			ds_48.u0 = <invalid>;
			cui16 dx_78;
			word16 cx_258;
			word16 di_259;
			if ((dx_78 | fn0015_03C6(SEQ(ds_48, 0x00), wLoc04_148, 0x00, (uint32) (*((bool) ds_48.u0 + 26)), out cx_258, out dx_78, out di_259)) == 0x00)
				return;
			uint16 v18_105 = wLoc08_145 + *((bool) ds_48.u0 + 26);
			wLoc08_145 = v18_105;
			wLoc06_144 += v18_105 <u 0x00;
		}
	}
	else
	{
		wLoc0A_149.u0 = 0x00;
		wLoc0C_150.u0 = 0x00;
		wLoc0E_151.u0 = 0x0A;
		goto l0015_0127;
	}
}

// 0015:01B0: Register word16 fn0015_01B0(Sequence Eq_107 ds_bx, Register out Eq_201 cxOut, Register out Eq_107 siOut)
// Called from:
//      fn0015_0308
word16 fn0015_01B0(Eq_107 ds_bx, union Eq_201 & cxOut, union Eq_107 & siOut)
{
	Eq_108 bx = (word16) ds_bx;
	Eq_107 ds = SLICE(ds_bx, selector, 16);
	Eq_107 dx_ax_493;
	Eq_107 dwLoc0C_496;
	struct Eq_209 Eq_283::* sp_137;
	Eq_201 si_143;
	Eq_108 di_19 = bx;
	Eq_201 wLoc0E_354 = 0x00;
	Eq_107 ax_23 = *((word32) ds_bx + 64) | *((word32) ds_bx + 62);
	if (ax_23 == 0x00)
	{
		word16 dx_502;
		fn0015_1532(ax_23, ds, out dx_502);
		Eq_107 dx_ax_499 = <invalid>;
		si_143 = (word32) bx + 54;
		sp_137 = fp - 0x14;
		dx_ax_493 = dx_ax_499;
		dwLoc0C_496 = dx_ax_499;
	}
	else
	{
		ui16 dx_32;
		uint16 ax_31 = fn0015_1532(ax_23, ds, out dx_32);
		struct Eq_233 Eq_283::* sp_110 = fp - 0x14;
		uint16 wLoc06_357 = ax_31;
		ui16 wLoc04_358 = dx_32;
		if (dx_32 != 0x00 || ax_31 >= ~0x0F)
		{
			Eq_201 cx_213;
			word16 di_503;
			fn0015_1E61(0x08, bx, ds, out cx_213, out di_503);
			cxOut = cx_213;
			siOut = wLoc1E;
			return 0x00;
		}
		Eq_107 ds_di_487;
		uint16 si_149;
		if (ax_31 >= 0x2000)
		{
			si_149 = 0x2000;
			ds_di_487 = ds_bx;
		}
		else
		{
			si_149 = ax_31;
			ds_di_487 = ds_bx;
		}
		while (true)
		{
			ds = SLICE(ds_di_487, selector, 16);
			struct Eq_363 Eq_283::* sp_51 = sp_110 - 2;
			(ss->*sp_51).t0000 = ds;
			di_19 = (word16) ds_di_487;
			(ss->*sp_51).tFFFFFFFE = di_19;
			Eq_108 ax_62 = si_149 + wLoc06_357;
			Eq_107 dx_65 = (bool) (ax_62 < 0x00) + wLoc04_358;
			Eq_107 dx_66 = dx_65;
			if (dx_65 != 0x00 || ax_62 > ~0x0F)
			{
				dx_66.u0 = 0x00;
				ax_62.u0 = ~0x0F;
			}
			(ss->*sp_51).tFFFFFFFC = dx_66;
			(ss->*sp_51).tFFFFFFFA = ax_62;
			cui16 ax_94 = *((word32) ds_di_487 + 22);
			Eq_107 ax_101 = SEQ(SLICE(ax_94, byte, 8) | 0x10, (byte) ax_94);
			(ss->*sp_51).tFFFFFFF8 = ax_101;
			sp_110 = (struct Eq_233 Eq_283::*) ((char *) &sp_51->t0000 + 2);
			if (fn0015_14F2(ax_101, (ss->*sp_51).tFFFFFFF8, (ss->*sp_51).tFFFFFFFA, (ss->*sp_51).t0000) != 0x00)
				break;
			si_149 >>= 0x01;
			if (si_149 >= 0x0C)
				continue;
			(ss->*sp_51).t0000 = ds;
			(ss->*sp_51).tFFFFFFFE = di_19;
			(ss->*sp_51).tFFFFFFFC.u0 = 0x02;
			Eq_107 ds_di_492 = <invalid>;
			si_149 *= 0x02;
			Eq_201 cx_162;
			word16 di_504;
			Eq_107 ax_160 = fn0015_1E61((ss->*sp_51).tFFFFFFFC, (ss->*sp_51).tFFFFFFFE, (ss->*sp_51).t0000, out cx_162, out di_504);
			Eq_107 ds_164 = SLICE(ds_di_492, selector, 16);
			word16 di_163 = (word16) ds_di_492;
			if (ax_160 == 0x00)
			{
				word16 ax_180 = 0x00 - (*((word32) ds_di_492 + 0x0A) < 0x01) + 0x01;
				Eq_107 si_182 = (ss->*sp_51).tFFF8;
				cxOut = cx_162;
				siOut = si_182;
				return ax_180;
			}
			(ss->*sp_51).tFFF6 = ds_164;
			(ss->*sp_51).wFFF4 = di_163;
			sp_110 = (struct Eq_233 Eq_283::*) &sp_51->tFFF8;
			ui16 dx_193;
			wLoc06_357 = fn0015_1532(ax_160, (ss->*sp_51).tFFF6, out dx_193);
			wLoc04_358 = dx_193;
			ds_di_487 = ds_di_492;
		}
		(ss->*sp_51).t0000.u0 = 0x00;
		(ss->*sp_51).tFFFFFFFE.u0 = 0x0C;
		(ss->*sp_51).tFFFFFFFC = wLoc04_358 - (wLoc06_357 < 66);
		(ss->*sp_51).tFFFFFFFA = wLoc06_357 - 66;
		sp_137 = (struct Eq_209 Eq_283::*) ((char *) &sp_51->t0000 + 2);
		si_143 = (word32) di_19 + fn0015_5390((ss->*sp_51).tFFFFFFFA, (ss->*sp_51).tFFFFFFFC, (ss->*sp_51).tFFFFFFFE, (ss->*sp_51).t0000) * 0x0C + 66;
		dx_ax_493 = SEQ(wLoc04_358, wLoc06_357);
		dwLoc0C_496 = SEQ(dx_66, ax_62);
	}
	ui32 v16_v14_349 = ds->*((word32) di_19 + 30) - dx_ax_493;
	ds->*((word32) di_19 + 30) = (word16) v16_v14_349;
	ds->*((word32) di_19 + 32) = SLICE(v16_v14_349, word16, 16);
	Eq_107 ax_250 = (word16) dx_ax_493;
	Eq_201 si_259 = si_143;
	Eq_107 dwLoc0C_484 = dwLoc0C_496;
	if (si_143 != 0x00)
	{
		struct Eq_279 Eq_283::* sp_264 = sp_137 - 2;
		(ss->*sp_264).t0000.u0 = 0x00;
		(ss->*sp_264).tFFFFFFFE.u0 = 0x0C;
		(ss->*sp_264).tFFFFFFFC = ds;
		(ss->*sp_264).tFFFFFFFA = di_19;
		word16 dx_274;
		uint16 ax_273 = fn0015_1532(ax_250, (ss->*sp_264).tFFFFFFFC, out dx_274);
		(ss->*sp_264).tFFFFFFFC = dx_274 - (ax_273 < 66);
		(ss->*sp_264).tFFFFFFFA = ax_273 - 66;
		wLoc0E_354 = (word32) di_19 + fn0015_5390((ss->*sp_264).tFFFFFFFA, (ss->*sp_264).tFFFFFFFC, (ss->*sp_264).tFFFFFFFE, (ss->*sp_264).t0000) * 0x0C + 0x36;
		dwLoc0C_484 = SEQ(dx_274, ax_273);
	}
	ui32 v19_v18_347 = Mem310[ds:di_19 + 0x1E:ui32] + dwLoc0C_484;
	ds->*((word32) di_19 + 30) = (word16) v19_v18_347;
	ds->*((word32) di_19 + 32) = SLICE(v19_v18_347, word16, 16);
	Eq_201 cx_322 = ds->*((word32) di_19 + 0x0A);
	do
	{
		ds->*((word16) si_505 + 4) = cx_322;
		cx_322 = si_505;
		si_259 = (word16) si_505 + 0x0C;
		si_505 = si_259;
	} while (wLoc0E_354 > si_505);
	ds->*((word32) bx + 0x0A) = si_505;
	Eq_107 si_339 = (ss->*sp_137).t0000;
	cxOut = si_505;
	siOut = si_339;
	return 0x01;
}

// 0015:0308: Register Eq_108 fn0015_0308(Sequence Eq_107 ds_bx, Register Eq_108 ax, Register out Eq_108 cxOut)
// Called from:
//      fn0015_03C6
Eq_108 fn0015_0308(Eq_107 ds_bx, Eq_108 ax, union Eq_108 & cxOut)
{
	struct Eq_553 Eq_107::* bx = (word16) ds_bx;
	Eq_107 ds = SLICE(ds_bx, selector, 16);
	Eq_108 ax_105;
	Eq_108 cx_110;
	struct Eq_553 Eq_107::* si_20 = bx;
	if (*((word32) ds_bx + 0x0A) == 0x00)
	{
		Eq_108 ax_25 = fn0015_01B0(ds_bx, out cx_110, out si_20);
		ds.u0 = <invalid>;
		ax_105 = ax_25;
		if (ax_25 == 0x00)
			goto l0015_0364;
	}
	Eq_108 bx_44 = (ds->*si_20).t000A;
	(ds->*si_20).t000A = ds->*((word32) bx_44 + 4);
	cx_110 = ax;
	Eq_575 di_52 = si_20 + (ax * 0x02) / 0x0E;
	if (ds->*di_52 == 0x00)
	{
		ds->*((word32) bx_44 + 6) = bx_44;
		ds->*((word32) bx_44 + 4) = bx_44;
	}
	else
	{
		Eq_108 ax_56 = ds->*di_52;
		ds->*((word32) bx_44 + 6) = ax_56;
		ds->*((word32) bx_44 + 4) = ds->*((word32) ax_56 + 4);
		ds->*((word32) (ds->*((word32) ax_56 + 4)) + 6) = bx_44;
		ds->*((word32) ax_56 + 4) = bx_44;
	}
	ds->*di_52 = bx_44;
	ax_105 = bx_44;
l0015_0364:
	cxOut = cx_110;
	return ax_105;
}

// 0015:0368: void fn0015_0368(Register (memptr (ptr16 Eq_626) Eq_623) ax, Register ui16 dx, Register (memptr (ptr16 Eq_626) Eq_625) bx)
// Called from:
//      fn0015_0510
void fn0015_0368(struct Eq_623 Eq_626::* ax, ui16 dx, struct Eq_625 Eq_626::* bx)
{
	if ((ds->*ax).ptr0004 == ax)
		(&(ds->*(ds->*bx).a0000))[dx * 0x02] = 0x00;
	else
	{
		(ds->*(ds->*ax).ptr0006).ptr0004 = (ds->*ax).ptr0004;
		(ds->*(ds->*ax).ptr0004).ptr0006 = (ds->*ax).ptr0006;
		Eq_649 si_41 = bx + (dx * 0x02) / 0x0C;
		if (ds->*si_41 == ax)
			ds->*si_41 = (ds->*ax).ptr0004;
	}
	(ds->*ax).ptr0004 = (ds->*bx).ptr000A;
	(ds->*bx).ptr000A = ax;
}

// 0015:03C6: Register Eq_108 fn0015_03C6(Sequence Eq_107 ds_bx, Register Eq_108 ax, Register Eq_172 dx, Stack Eq_108 dwArg02, Register out Eq_174 cxOut, Register out Eq_107 dxOut, Register out ptr16 diOut)
// Called from:
//      fn0015_010C
//      fn0015_05E2
//      fn0015_0838
//      fn0015_0B20
Eq_108 fn0015_03C6(Eq_107 ds_bx, Eq_108 ax, Eq_172 dx, Eq_108 dwArg02, union Eq_174 & cxOut, union Eq_107 & dxOut, ptr16 & diOut)
{
	Eq_108 bx = (word16) ds_bx;
	Eq_107 ds = SLICE(ds_bx, selector, 16);
	cu16 wArg02 = (word16) dwArg02;
	word16 wArg04 = SLICE(dwArg02, word16, 16);
	int32 dx_ax_278 = (word32) *((word32) ds_bx + 30) + SEQ(wArg04 + (wArg02 < 0x0FFF), wArg02 + 0x0FFF & 0xF000);
	cup16 ax_29 = (word16) dx_ax_278;
	byte bLoc16_292 = (byte) dx;
	cup16 dx_32 = SLICE(dx_ax_278, word16, 16);
	byte ah_46 = SLICE(ax_29, byte, 8);
	if (dx_32 >= *((word32) ds_bx + 40) && (dx_32 > *((word32) ds_bx + 40) || ax_29 > *((word32) ds_bx + 38)))
		fn0015_1E61(0x07, bx, ds, out cx, out di);
	else
	{
		cui16 wLoc14_290;
		if (ax == 0x03)
		{
			cui16 ax_52 = 0x00 - ((SEQ(ah_46, bLoc16_292) & 0x01) >= 0x01);
			wLoc14_290 = SEQ(SLICE(ax_52 & 0x0100, byte, 8) | 0x20, (byte) (ax_52 & 0x0100));
		}
		else
			wLoc14_290 = 0x1000;
		Eq_107 ax_77 = *((word32) ds_bx + 22) | wLoc14_290;
		Eq_107 dx_85;
		Eq_108 ax_83 = fn0015_131C(SLICE(ax_77, byte, 8), ax_77, dwArg02, out dx_85);
		if ((dx_85 | ax_83) != 0x00)
		{
			Eq_107 ax_100 = fn0015_0308(ds_bx, ax, out cx);
			Eq_107 ds_103 = <invalid>;
			if (ax_100 != 0x00)
			{
				word16 ax_169;
				ds_103->*((word32) ax_100 + 8) = ax_83;
				ds_103->*((word32) ax_100 + 0x0A) = dx_85;
				*((word32) dx_85 + 0x0C) = ax | 0xCAD0;
				*dx_85 = bx;
				*((word32) dx_85 + 2) = ds;
				*((word32) dx_85 + 4) = ax_100;
				*((word32) dx_85 + 6) = ds_103;
				*((word32) dx_85 + 0x0A) = 0x00;
				word16 dx_410;
				fn0015_1532(ax_100, dx_85, out dx_410);
				Eq_107 dx_ax_406 = <invalid>;
				word16 ax_145 = (word16) dx_ax_406;
				if (ax != 0x01)
				{
					if (ax != 0x03)
						ax_169 = fn0015_09CA(ax_145, &Eq_1387::t0000, out cx);
					else
						ax_169 = fn0015_05B4(SEQ(dx_85, 0x00), dx);
				}
				else
					ax_169 = fn0015_0782(SEQ(dx_85, 0x00), ax_145, ds_bx, out cx);
				ds_103->*ax_100 = ax_169;
				ds_103->*((word32) ax_100 + 2) = 0x8000;
				ui32 v26_v25_280 = Mem215[ds_103:bx + 0x1E:ui32] + dx_ax_406;
				ds_103->*((word32) bx + 30) = (word16) v26_v25_280;
				ds_103->*((word32) bx + 32) = SLICE(v26_v25_280, word16, 16);
				cxOut = cx;
				dxOut = dx_85;
				diOut = di;
				return ax_83;
			}
			fn0015_13CE(ax_100, dx_85);
		}
	}
	cxOut = cx;
	dxOut.u0 = 0x00;
	diOut = di;
	return 0x00;
}

// 0015:0510: Register word16 fn0015_0510(Sequence (ptr32 Eq_47) ds_bx, Register word16 ax)
// Called from:
//      fn0015_0052
word16 fn0015_0510(struct Eq_47 * ds_bx, word16 ax)
{
	Eq_107 ds = SLICE(ds_bx, selector, 16);
	word16 wLoc12_148;
	Eq_107 ax_114;
	struct Eq_623 Eq_626::* ax_21 = ds_bx->ptr0004;
	word16 ax_17 = ds_bx->w0000;
	struct Eq_868 * dx_18 = ds_bx->ptr0002;
	cui16 ax_27 = SEQ(SLICE(ax_21, byte, 8), ds_bx->t000C);
	word16 dx_200;
	fn0015_1532(ax_27 & 0x07, ds, out dx_200);
	Eq_107 dx_ax_199 = <invalid>;
	Eq_107 ax_36 = (word16) dx_ax_199;
	struct Eq_887 * ptrLoc06_143 = ax_17;
	if (ax != 0x00)
	{
		ui32 dx_ax_129 = SEQ(ptrLoc06_143->w0020, ptrLoc06_143->w001E) - dx_ax_199;
		ax_114 = (word16) dx_ax_129;
		cup16 dx_58 = SLICE(dx_ax_129, word16, 16);
		if (dx_58 <= ptrLoc06_143->w0024 && (dx_58 < ptrLoc06_143->w0024 || ax_114 < ptrLoc06_143->t0022))
		{
			wLoc12_148 = 0x00;
l0015_0595:
			if (wLoc12_148 == 0x00)
				return 0x00;
			ds_bx->t000C.u1 = 0x00;
			fn0015_13CE(ax_114, ds);
			return 0x01;
		}
	}
	fn0015_0368(ax_21, ax_27 & 0x07, &Eq_626::t0000);
	ui32 v18_v17_127 = SEQ(dx_18->w0020, dx_18->w001E) - dx_ax_199;
	dx_18->w001E = (word16) v18_v17_127;
	dx_18->w0020 = SLICE(v18_v17_127, word16, 16);
	ax_114 = ax_36;
	wLoc12_148 = 0x01;
	goto l0015_0595;
}

// 0015:05B4: Register Eq_172 fn0015_05B4(Sequence (ptr32 Eq_823) ds_bx, Register Eq_172 ax)
// Called from:
//      fn0015_03C6
Eq_172 fn0015_05B4(struct Eq_823 * ds_bx, Eq_172 ax)
{
	ds_bx->w000A = 0x01;
	ds_bx->w0008 = 0x0668;
	ds_bx->b0013 = 0x00 - ((ax & 0x02) >= 0x01) & 0x02;
	ds_bx->w0010 = 0x00;
	ds_bx->w000E = 0x00;
	return 0x00;
}

// 0015:05E2: Register Eq_172 fn0015_05E2(Register Eq_172 ax, Register Eq_971 bx, Stack Eq_108 wArg02, Stack cu16 wArg04, Register out Eq_974 cxOut, Register out Eq_975 dxOut)
// Called from:
//      fn0015_0A48
//      fn0015_0B20
Eq_172 fn0015_05E2(Eq_172 ax, Eq_971 bx, Eq_108 wArg02, cu16 wArg04, union Eq_974 & cxOut, union Eq_975 & dxOut)
{
	struct Eq_976 Eq_1040::* sp_126 = fp - 0x0A;
	Eq_172 di_118 = ax;
	Eq_107 v12_24 = (bool) (wArg02 < 0x14) + wArg04;
	Eq_107 ds_si_200 = bx;
	do
	{
		struct Eq_1037 Eq_1040::* sp_32 = sp_126 - 2;
		(ss->*sp_32).t0000 = v12_24;
		(ss->*sp_32).tFFFFFFFE = (word32) wArg02 + 20;
		Eq_975 dx_46;
		Eq_974 cx_117;
		cui16 ax_44 = fn0015_03C6(ds_si_200, 0x03, di_118, (ss->*sp_32).tFFFFFFFE, out cx_117, out dx_46, out di_118);
		struct Eq_14 Eq_18::* si_37 = (word16) ds_si_200;
		Eq_107 ds_48 = <invalid>;
		sp_126 = (struct Eq_976 Eq_1040::*) ((char *) &sp_32->t0000 + 2);
		if ((dx_46 | ax_44) != 0x00)
		{
			cxOut = cx_117;
			dxOut = dx_46;
			return ax_44 + 0x14;
		}
		cui16 dx_73;
		Eq_108 si_74;
		cui16 ax_72 = fn0015_0052(si_37, out dx_73, out si_74);
		int32 dx_ax_148 = SEQ((word32) v12_24 + (wArg02 < 61461), (word32) wArg02 + 4115 & 0xF000) + ds_48->*((word32) si_74 + 30);
		cup16 ax_89 = (word16) dx_ax_148;
		cup16 dx_92 = SLICE(dx_ax_148, word16, 16);
		if (dx_92 > ds_48->*((word32) si_74 + 40) || dx_92 >= ds_48->*((word32) si_74 + 40) && ax_89 > ds_48->*((word32) si_74 + 38))
			break;
		ds_si_200 = SEQ(ds_48, si_74);
		if ((dx_73 | ax_72) != 0x00)
			continue;
		(ss->*sp_32).t0000 = ds_48;
		(ss->*sp_32).tFFFFFFFE = si_74;
		(ss->*sp_32).tFFFFFFFC.u0 = 0x02;
		Eq_107 ds_119 = <invalid>;
		sp_126 = (struct Eq_976 Eq_1040::*) ((char *) &sp_32->t0000 + 0x0000FFF8);
		ds_si_200 = SEQ(ds_119, si_74);
	} while (fn0015_1E61((ss->*sp_32).tFFFFFFFC, (ss->*sp_32).tFFFFFFFE, (ss->*sp_32).t0000, out cx_117, out di_118) != 0x00);
	cxOut = cx_117;
	dxOut.u0 = 0x00;
	return 0x00;
}

// 0015:0782: Register word16 fn0015_0782(Sequence (ptr32 Eq_811) ds_bx, Register word16 ax, Stack Eq_107 ptrArg02, Register out ptr16 cxOut)
// Called from:
//      fn0015_03C6
word16 fn0015_0782(struct Eq_811 * ds_bx, word16 ax, Eq_107 ptrArg02, ptr16 & cxOut)
{
	struct Eq_1093 Eq_1121::* bx = (word16) ds_bx;
	ds_bx->w000E = 0x00;
	ds_bx->w0010 = (char *) &bx->t0010 + 4;
	ds_bx->w0008 = 0x09A0;
	cxOut = fn0015_07AC(*((word32) ptrArg02 + 24), ax, bx);
	return 0x01;
}

// 0015:07AC: Register Eq_1118 fn0015_07AC(Register Eq_108 ax, Register word16 dx, Register (memptr (ptr16 Eq_1121) Eq_1093) bx)
// Called from:
//      fn0015_0782
Eq_1118 fn0015_07AC(Eq_108 ax, word16 dx, struct Eq_1093 Eq_1121::* bx)
{
	Eq_1118 bx_45;
	Eq_1118 di_26 = (ds->*bx).t0010;
	(ds->*bx).t000E = di_26;
	word16 bx_29 = bx - di_26 + dx / 18;
	Eq_1118 cx_40 = bx_29 + (di_26 - (uint16) ((uint32) bx_29 % ax));
	(ds->*bx).t0010 = cx_40;
	Eq_1118 cx_42 = cx_40 - ax;
	if (cx_42 <= di_26)
		bx_45 = di_26;
	else
	{
		bx_45 = di_26;
		do
		{
			word16 ax_50 = bx_45 + ax;
			ds->*bx_45 = ax_50;
			bx_45 = ax_50;
		} while (ax_50 < cx_42);
	}
	(ds->*bx_45).u0 = 0x00;
	return cx_42;
}

// 0015:0838: Register Eq_1153 fn0015_0838(Sequence (ptr32 Eq_1154) ds_bx, Register out Eq_1153 cxOut, Register out (ptr16 Eq_1156) dxOut)
// Called from:
//      fn0015_0A48
Eq_1153 fn0015_0838(struct Eq_1154 * ds_bx, union Eq_1153 & cxOut, struct Eq_1156 & dxOut)
{
	Eq_108 bx = (word16) ds_bx;
	Eq_107 ds = SLICE(ds_bx, selector, 16);
	word16 si_20 = ds_bx->w0002;
	struct Eq_1165 Eq_1204::* sp_113 = fp - 20;
	word16 wLoc04_222 = si_20;
	struct Eq_1170 * ds_si_308 = SEQ(ds, si_20);
	if (ds_bx->w0002 != 0x00)
	{
		do
		{
l0015_084B:
			struct Eq_1183 Eq_107::* si_25 = (word16) ds_si_308;
			ds = SLICE(ds_si_308, selector, 16);
			if (ds_si_308->w0000 != 0x00)
			{
				struct Eq_1156 * dx_30 = ds_si_308->ptr000A;
				union Eq_107 Eq_1204::* sp_36 = sp_113 - 2;
				ss->*sp_36 = ds;
				Eq_1153 ax_40 = dx_30->t000E;
				if (ax_40 != 0x00)
				{
					dx_30->t000E = dx_30->*ax_40;
					++dx_30->w000A;
					wLoc0E = ax_40;
					wLoc0C = dx_30;
				}
				ds = ss->*sp_36;
				if (ax_40 != 0x00)
				{
					ds->*((word32) bx + 2) = si_25;
					cxOut = ax_40;
					dxOut = wLoc0C;
					return wLoc0E;
				}
				(ds->*si_25).w0000 = 0x00;
			}
			word16 si_70 = (ds->*si_25).w0004;
			ds_si_308 = SEQ(ds, si_70);
		} while (si_70 != wLoc04_222);
	}
	Eq_1153 cx_105;
	if (ds->*((word32) bx + 24) == 0x00)
	{
		struct Eq_1217 Eq_1204::* sp_174 = sp_113 - 2;
		(ss->*sp_174).t0000 = ds;
		(ss->*sp_174).tFFFFFFFE = bx;
		(ss->*sp_174).tFFFFFFFC.u0 = 0x04;
		word16 di_314;
		fn0015_1E61((ss->*sp_174).tFFFFFFFC, (ss->*sp_174).tFFFFFFFE, (ss->*sp_174).t0000, out cx_105, out di_314);
	}
	else
	{
		Eq_108 wLoc06_236 = ds->*((word32) bx + 26);
		do
		{
			struct Eq_1305 Eq_1204::* sp_91 = sp_113 - 2;
			(ss->*sp_91).t0000.u0 = 0x00;
			(ss->*sp_91).tFFFFFFFE = wLoc06_236;
			ds.u0 = <invalid>;
			sp_113 = (struct Eq_1165 Eq_1204::*) ((char *) &sp_91->t0000 + 2);
			cui16 dx_104;
			word16 di_315;
			if ((dx_104 | fn0015_03C6(SEQ(ds, bx), 0x01, 0x00, (ss->*sp_91).tFFFFFFFE, out cx_105, out dx_104, out di_315)) != 0x00)
			{
				struct Eq_1183 Eq_107::* si_119 = ds->*((word32) bx + 2);
				wLoc04_222 = (ds->*si_119).w0004;
				ds_si_308 = SEQ(ds, si_119);
				goto l0015_084B;
			}
			Eq_1269 dx_ax_217 = SEQ(ds->*((word32) bx + 32), ds->*((word32) bx + 30)) + (uint32) wLoc06_236;
			cup16 ax_125 = (word16) dx_ax_217;
			cup16 dx_128 = SLICE(dx_ax_217, word16, 16);
			if (dx_128 >= ds->*((word32) bx + 40) && (dx_128 > ds->*((word32) bx + 40) || ax_125 > ds->*((word32) bx + 38)))
				break;
			Eq_108 v19_141 = wLoc06_236 >> 0x01;
			wLoc06_236 = v19_141;
			if (ds->*((word32) bx + 24) + 0x14 <= v19_141)
				continue;
			(ss->*sp_91).t0000 = ds;
			(ss->*sp_91).tFFFFFFFE = bx;
			(ss->*sp_91).tFFFFFFFC.u0 = 0x02;
			wLoc06_236 = v19_141 * 0x02;
			ds.u0 = <invalid>;
			sp_113 = (struct Eq_1165 Eq_1204::*) ((char *) &sp_91->t0000 + 0x0000FFF8);
			word16 di_316;
		} while (fn0015_1E61((ss->*sp_91).tFFFFFFFC, (ss->*sp_91).tFFFFFFFE, (ss->*sp_91).t0000, out cx_105, out di_316) != 0x00);
	}
	cxOut = cx_105;
	dxOut = 0x00;
	return 0x00;
}

// 0015:09CA: Register word16 fn0015_09CA(Register word16 ax, Register (memptr (ptr16 Eq_1387) Eq_831) bx, Register out Eq_832 cxOut)
// Called from:
//      fn0015_03C6
word16 fn0015_09CA(word16 ax, struct Eq_831 Eq_1387::* bx, union Eq_832 & cxOut)
{
	word16 bx_16 = bx - &bx->w0014 + ax;
	struct Eq_1375 Eq_1387::* bx_22 = &bx->w0014 + SEQ(SLICE(bx_16 - 0x06, byte, 8), (byte) (bx_16 - 0x06) & 252);
	(ds->*bx_22).t0000.u0 = 0x01;
	(ds->*bx).w000E = &bx->w0014;
	(ds->*bx_22).ptr0004 = bx_22;
	(ds->*bx_22).ptr0002 = bx_22;
	(ds->*bx).ptr0010 = bx_22;
	if (((ds->*bx).b000C & 0x07) == 0x02)
		(ds->*bx).w0012 = 0x08;
	else
	{
		cu16 ax_36 = *((word32) (ds->*bx).t0000 + 24);
		(ds->*bx).w0012 = (ax_36 - 0x05 & ~(0x00 - (ax_36 < 0x05))) + 0x08;
	}
	struct Eq_1434 Eq_1387::* bx_52 = bx_22 - &bx->w0014;
	(ds->*bx_22).ptrFFFFFFFE = bx_52;
	(ds->*bx).w0014 = SEQ(SLICE(bx_52, byte, 8), (byte) bx_52 | 0x02);
	(ds->*bx).ptr0018 = bx_22;
	(ds->*bx).ptr0016 = (ds->*bx_22).ptr0002;
	(ds->*(ds->*bx_22).ptr0002).ptr0004 = (struct Eq_1375 Eq_1387::*) &bx->w0014;
	(ds->*bx_22).ptr0002 = (struct Eq_1375 Eq_1387::*) &bx->w0014;
	(ds->*bx).w0008 = 0x0E08;
	word16 ax_71 = (ds->*bx).w0014;
	cxOut = &bx->w0014;
	return SEQ(SLICE(ax_71, byte, 8), (byte) ax_71 & 252);
}

// 0015:0A48: Register Eq_172 fn0015_0A48(Stack cui16 wArg04, Stack Eq_108 wArg06, Stack cu16 wArg08, Stack Eq_1484 ptrArg0A, Register out Eq_1485 cxOut, Register out (ptr16 Eq_1486) dxOut, Register out ptr16 siOut, Register out Eq_1488 diOut)
// Called from:
//      fn0015_167A
//      fn0015_1708
Eq_172 fn0015_0A48(cui16 wArg04, Eq_108 wArg06, cu16 wArg08, Eq_1484 ptrArg0A, union Eq_1485 & cxOut, struct Eq_1486 & dxOut, ptr16 & siOut, union Eq_1488 & diOut)
{
	Eq_108 wArg0A_270 = (word16) ptrArg0A;
	Eq_107 psegArg0C_249 = SLICE(ptrArg0A, selector, 16);
	byte bArg04_279 = (byte) wArg04;
	if (*((word32) ptrArg0A + 20) == 48813)
	{
		struct Eq_1486 * wLoc04_264;
		Eq_1485 cx_129;
		Eq_172 wLoc06_263;
		mp16 sp_138 = fp - 0x0C;
		Eq_108 ax_26 = *((word32) psegArg0C_249 + 24);
		if (wArg08 <= 0x00 && (wArg08 < 0x00 || wArg06 <= ax_26))
		{
			if (wArg08 == 0x00 && wArg06 == 0x00)
			{
				word16 di_359;
				fn0015_1E61(0x04, wArg0A_270, psegArg0C_249, out cx_129, out di_359);
				sp_138 = fp - 22;
				wLoc04_264 = 0x00;
				wLoc06_263.u0 = 0x00;
			}
			else
			{
				struct Eq_1486 * dx_154;
				Eq_172 ax_149 = fn0015_0838(SEQ(psegArg0C_249, 0x00), out cx_129, out dx_154);
				Eq_107 ds_153 = <invalid>;
				wLoc06_263 = ax_149;
				wLoc04_264 = dx_154;
				if ((dx_154 | ax_149) != 0x00 && (bArg04_279 & 0x01) != 0x00)
				{
					Eq_108 cx_173 = *((word32) ds_153 + 24);
					Eq_172 di_176 = ax_149;
					for (cx_129 = cx_173 >> 0x01; cx_129 != 0x00; --cx_129)
					{
						dx_154->*di_176 = 0x00;
						di_176 = (word16) di_176 + 2;
					}
					if (cx_173 >> 0x01 < 0x00)
						dx_154->*di_176 = 0x00;
				}
			}
		}
		else
		{
			struct Eq_1486 * dx_107;
			Eq_172 ax_103;
			Eq_108 ax_36 = *((word32) psegArg0C_249 + 28);
			if (wArg08 <= 0x00 && (wArg08 < 0x00 || wArg06 <= ax_36))
				ax_103 = fn0015_0B20(SEQ(SLICE(wArg04, byte, 8), (byte) wArg04 & ~0x02), wArg06, 0x00, out cx_129, out dx_107);
			else
				ax_103 = fn0015_05E2(SEQ(SLICE(wArg04, byte, 8), (byte) wArg04 & ~0x02), 0x00, wArg06, wArg08, out cx_129, out dx_107);
			sp_138 = fp - 0x0C;
			wLoc06_263 = ax_103;
			wLoc04_264 = dx_107;
		}
		struct Eq_1562 Eq_1566::* sp_197 = sp_138 + 2;
		ptr16 si_202 = (ss->*sp_197).ptr0000;
		Eq_1488 di_204 = (ss->*sp_197).t0002;
		cxOut = cx_129;
		dxOut = wLoc04_264;
		siOut = si_202;
		diOut = di_204;
		return wLoc06_263;
	}
	else
	{
		Eq_1485 cx_221;
		word16 di_358;
		fn0015_1E61(0x0A, 0x00, 0x00, out cx_221, out di_358);
		cxOut = cx_221;
		dxOut = 0x00;
		siOut = wLoc14;
		diOut = wLoc12;
		return 0x00;
	}
}

// 0015:0B20: Register Eq_172 fn0015_0B20(Register Eq_172 ax, Register Eq_108 dx, Register Eq_971 bx, Register out Eq_1615 cxOut, Register out Eq_1616 dxOut)
// Called from:
//      fn0015_0A48
Eq_172 fn0015_0B20(Eq_172 ax, Eq_108 dx, Eq_971 bx, union Eq_1615 & cxOut, union Eq_1616 & dxOut)
{
	struct Eq_1632 * ds_di_379;
	word16 wLoc06_278;
	cu16 cx_32 = SEQ(SLICE((word32) dx + 5, byte, 8), (byte) ((word32) dx + 5) & 252);
	Eq_1616 dx_131 = ~(0x00 - (cx_32 < 0x08));
	cui16 cx_38 = cx_32 - 0x08 & dx_131;
	Eq_172 wLoc14_273 = ax;
	struct Eq_1653 Eq_1694::* sp_135 = fp - 26;
	Eq_1615 cx_144 = cx_38 + 0x08;
	Eq_108 si_128 = cx_38 + 0x08;
	word16 di_45 = Mem27[ds:(ax & 0x02) + (ax & 0x02) + bx:word16];
	wLoc14_273 = ax;
	if (di_45 != 0x00)
	{
		wLoc06_278 = di_45;
		ds_di_379 = SEQ(ds, di_45);
l0015_0B55:
		do
		{
			struct Eq_1693 * ds_51 = SLICE(ds_di_379, selector, 16);
			struct Eq_1632 * ds_di_376 = ds_di_379;
			if (ds_di_379->w0000 >= si_128)
			{
				struct Eq_1693 * Eq_1694::* sp_64 = sp_135 - 2;
				ss->*sp_64 = ds_51;
				word16 di_74;
				Eq_172 ax_72 = fn0015_0C32(si_128, wLoc14_387, &Eq_1706::t0000, out cx_144, out dx_131, out si_128, out di_74);
				struct Eq_1693 * ds_85 = ss->*sp_64;
				if ((dx_131 | ax_72) != 0x00)
				{
					*((word16) bx + (ax & 0x02) * 0x02) = di_74;
					cxOut = cx_144;
					dxOut = dx_131;
					return ax_72;
				}
				ds_di_376 = (struct Eq_1632 *) di_74;
			}
			ds = SLICE(ds_di_376, selector, 16);
			word16 di_108 = ds_di_376[2];
			wLoc14_273 = wLoc14_387;
			ds_di_379 = SEQ(ds, di_108);
			wLoc14_387 = wLoc14_273;
		} while (di_108 != wLoc06_278);
	}
	byte bLoc13_311 = SLICE(wLoc14_273, byte, 8);
	byte bLoc14_289 = (byte) wLoc14_273;
	if ((bLoc14_289 & 0x02) != 0x00 && ((bLoc14_289 & 0x40) == 0x00 && Mem115[ds:bx + 0x32:word16] != 0x00))
	{
		<anonymous> Eq_2::* ax_126 = ds->*((word16) bx + 50);
		Eq_108 ax_142;
		(0015->*ax_126)();
		if (ax_142 >= si_128)
		{
			wLoc14_273 = SEQ(bLoc13_311, bLoc14_289 | 0x40);
			goto l0015_0B8C;
		}
	}
	if ((bLoc14_289 & 0x10) == 0x00)
	{
		struct Eq_1761 Eq_1694::* sp_157 = sp_135 - 2;
		(ss->*sp_157).w0000 = 0x00;
		(ss->*sp_157).tFFFFFFFE = ds->*((word16) bx + 26);
		ds.u0 = <invalid>;
		sp_135 = (struct Eq_1653 Eq_1694::*) (&sp_157->w0000 + 1);
		cui16 dx_170;
		word16 di_386;
		dx_131 = dx_170 | fn0015_03C6(SEQ(ds, bx), ax & 0x02, 0x00, (ss->*sp_157).tFFFFFFFE, out cx_144, out dx_170, out di_386);
		wLoc14_273 = wLoc14_315;
		if (dx_131 != 0x00)
		{
l0015_0B8C:
			struct Eq_1792 Eq_107::* di_263 = SEQ(ds, bx)[ax & 0x02];
			wLoc06_278 = (ds->*di_263).w0004;
			ds_di_379 = SEQ(ds, di_263);
			goto l0015_0B55;
		}
	}
	wLoc14_315 = wLoc14_273;
	if ((bLoc14_289 & 0x20) == 0x00)
	{
		cu16 ax_197 = ((word32) si_128 + 0x0FFF & 0xF000) + ds->*((word16) bx + 30);
		cup16 dx_200 = (bool) (ax_197 < 0x00) + ds->*((word16) bx + 32);
		if (dx_200 <= ds->*((word16) bx + 40) && (dx_200 < ds->*((word16) bx + 40) || ax_197 <= ds->*((word16) bx + 38)))
		{
			struct Eq_1827 Eq_1694::* sp_222 = sp_135 - 2;
			(ss->*sp_222).w0000 = 0x00;
			(ss->*sp_222).tFFFFFFFE = si_128;
			Eq_1615 cx_234;
			Eq_1616 dx_239;
			Eq_172 ax_232 = fn0015_05E2(wLoc14_273, bx, (ss->*sp_222).tFFFFFFFE, (ss->*sp_222).w0000, out cx_234, out dx_239);
			cxOut = cx_234;
			dxOut = dx_239;
			return ax_232;
		}
	}
	cxOut = cx_144;
	dxOut.u0 = 0x00;
	return 0x00;
}

// 0015:0C32: Register Eq_108 fn0015_0C32(Register Eq_108 ax, Register Eq_172 dl, Register (memptr (ptr16 Eq_1706) Eq_1704) bx, Register out Eq_108 cxOut, Register out (ptr16 Eq_1706) dxOut, Register out Eq_1707 siOut, Register out ptr16 diOut)
// Called from:
//      fn0015_0B20
Eq_108 fn0015_0C32(Eq_108 ax, Eq_172 dl, struct Eq_1704 Eq_1706::* bx, union Eq_108 & cxOut, struct Eq_1706 & dxOut, union Eq_1707 & siOut, ptr16 & diOut)
{
	byte ah_310 = SLICE(ax, byte, 8);
	byte bLoc0C_362 = (byte) dx;
	Eq_108 wLoc0E_318 = ax;
	struct Eq_1860 Eq_2062::* sp_160 = fp - 20;
	Eq_108 bx_27 = (ds->*bx).t000E;
	Eq_108 wLoc06_323 = 0x00;
	bx_240 = bx_27;
	do
	{
		Eq_108 bx_240;
		Eq_108 cx_274 = ds->*bx_240;
		byte cl_38 = (byte) cx_274;
		byte ch_40 = SLICE(cx_274, byte, 8);
		if (ax <= cx_274)
		{
			Eq_108 bx_119;
			Eq_108 wLoc08_327;
			Eq_108 cx_117 = SEQ(ch_40, cl_38 & 252) - ax;
			if ((ds->*bx).t0012 > cx_117)
			{
				bx_119 = ds->*((word16) bx_240 + 2);
				ds->*((word32) (ds->*((word16) bx_240 + 4)) + 2) = bx_119;
				ds->*((word32) (ds->*((word16) bx_240 + 2)) + 4) = ds->*((word16) bx_240 + 4);
				ds->*bx_240 |= 0x01;
				Eq_108 ax_128 = ds->*bx_240;
				Eq_108 ax_132 = SEQ(SLICE(ax_128, byte, 8), (byte) ax_128 & 252);
				word16 di_133 = bx_240 + ax_132;
				Eq_108 ax_135 = (ds->*di_133).t0000;
				(ds->*di_133).t0000 = SEQ(SLICE(ax_135, byte, 8), (byte) ax_135 | 0x02);
				cx_117 = bx_240;
				wLoc0E_318 = ax_132;
				wLoc08_327 = bx_240;
			}
			else if ((bLoc0C_362 & 0x06) != 0x00)
			{
				cui16 ax_81 = SEQ(ah_310, ds->*bx_240) & 0x02 | ax;
				ds->*bx_240 = SEQ(SLICE(ax_81, byte, 8), (byte) ax_81 | 0x01);
				ds->*((word32) (ds->*((word16) bx_240 + 4)) + 2) = ds->*((word16) bx_240 + 2);
				ds->*((word32) (ds->*((word16) bx_240 + 2)) + 4) = ds->*((word16) bx_240 + 4);
				bx_119 = bx_240 + ax;
				Mem96[ds:bx_119 - 0x02 + cx_117:word16] = cx_117;
				ds->*bx_119 = SEQ(SLICE(cx_117, byte, 8), (byte) cx_117 | 0x02);
				Eq_108 ax_106 = (ds->*bx).t0010;
				ds->*((word32) bx_119 + 4) = ax_106;
				ds->*((word32) bx_119 + 2) = ds->*((word32) ax_106 + 2);
				ds->*((word32) (ds->*((word32) ax_106 + 2)) + 4) = bx_119;
				ds->*((word32) ax_106 + 2) = bx_119;
				wLoc08_327 = bx_240;
			}
			else
			{
				word16 ax_51 = cx_117 + bx_240;
				ds->*((word16) ax_51 - 2) = cx_117;
				ds->*bx_240 = SEQ(SLICE(cx_117, byte, 8), (byte) cx_117 | 0x02);
				word16 si_63 = ax_51 + ax;
				bx_119 = ds->*((word16) bx_240 + 2);
				ds->*si_63 |= 0x02;
				ds->*ax_51 = SEQ(SLICE(ax, byte, 8), (byte) ax | 0x01);
				wLoc08_327 = ax_51;
			}
			(ds->*bx).t000E = bx_119;
			if ((bLoc0C_362 & 0x01) != 0x00)
			{
				struct Eq_1706 * Eq_2062::* sp_161 = sp_160 - 2;
				ss->*sp_161 = ds;
				Eq_2066 di_158 = (word32) wLoc08_327 + 2;
				struct Eq_1706 * es_163 = ss->*sp_161;
				Eq_108 cx_165 = wLoc0E_318 - 0x02 >> 0x01;
				for (cx_117 = cx_165; cx_117 != 0x00; --cx_117)
				{
					es_163->*di_158 = 0x00;
					di_158 = (word16) di_158 + 2;
				}
				if (cx_165 < 0x00)
					es_163->*di_158 = 0x00;
			}
			if ((bLoc0C_362 & 0x02) != 0x00 && ds->*((word32) bx_119 + 2) == ds->*((word32) bx_119 + 4))
			{
				Eq_108 ax_193 = ds->*(ds->*((word32) (ds->*bx).t0010 + 2));
				(ds->*bx).ptr0004->w0000 = SEQ(SLICE(ax_193, byte, 8), (byte) ax_193 & 252);
				struct Eq_2136 * es_bx_202 = (ds->*bx).ptr0004;
				es_bx_202->b0003 |= 0x80;
			}
			++(ds->*bx).w000A;
			Eq_1707 si_223 = (ss->*sp_160).t0000;
			ptr16 di_225 = (ss->*sp_160).ptr0002;
			cxOut = cx_117;
			dxOut = ds;
			siOut = si_223;
			diOut = di_225;
			return (word32) wLoc08_327 + 2;
		}
		if (wLoc06_323 < cx_274)
			wLoc06_323 = cx_274;
		bx_240 = ds->*((word16) bx_240 + 2);
		if (bx_240 != bx_27)
			continue;
		if ((bLoc0C_362 & 0x02) == 0x00 || (bLoc0C_362 & 0x40) != 0x00)
			break;
		struct Eq_2187 * es_bx_253 = (ds->*bx).ptr0000;
		if (Mem239[es_bx_253 + 0x34:word16] == 0x00)
			break;
		<anonymous> Eq_2::* ax_258 = es_bx_253->ptr0034;
		Eq_108 ax_272;
		(0015->*ax_258)();
		ah_310 = (ss->*fp).b000B;
		wLoc06_323 = ax_272;
		if (ax_272 < ax)
			break;
		Eq_108 bx_280 = (ds->*bx).t000E;
		bx_240 = bx_280;
	} while (bx_280 != 0x00);
	(ds->*bx).ptr0004->w0000 = SEQ(SLICE(wLoc06_323, byte, 8), (byte) wLoc06_323 & 252);
	Eq_1707 si_304 = (ss->*sp_160).t0000;
	ptr16 di_306 = (ss->*sp_160).ptr0002;
	cxOut = cx_274;
	dxOut = 0x00;
	siOut = si_304;
	diOut = di_306;
	return 0x00;
}

// 0015:131C: Register word16 fn0015_131C(Register byte ah, Stack Eq_107 wArg04, Stack Eq_108 dwArg06, Register out (ptr16 Eq_756) dxOut)
// Called from:
//      fn0015_03C6
//      fn0015_1902
word16 fn0015_131C(byte ah, Eq_107 wArg04, Eq_108 dwArg06, struct Eq_756 & dxOut)
{
	byte bArg04_219 = (byte) wArg04;
	word16 wArg08 = SLICE(dwArg06, word16, 16);
	cup16 wArg06 = (word16) dwArg06;
	byte bh_19 = SLICE(wArg04, byte, 8);
	byte bl_39 = (byte) wArg04;
	cui16 si_104 = 0x32;
	Eq_108 dwArg06_347 = dwArg06;
	if ((bh_19 & 0x10) != 0x00)
	{
		if (wArg08 != 0x00)
		{
l0015_133E:
			dwArg06_347.u0 = 0xFFF0;
			goto l0015_1348;
		}
		dwArg06_347 = dwArg06;
		if (wArg06 > ~0x0F)
			goto l0015_133E;
	}
l0015_1348:
	uint16 wArg08_198 = SLICE(dwArg06_347, word16, 16);
	Eq_108 wArg06_195 = (word16) dwArg06_347;
	if ((bh_19 & 0x01) != 0x00)
		si_104 = 114;
	if ((bl_39 & 0x01) != 0x00)
		si_104 |= 0x2000;
	Eq_107 ax_108 = SEQ(ah, bl_39 & 0x04);
	if ((bl_39 & 0x04) != 0x00)
	{
		ax_108 = fn0015_1558(wArg06_195, wArg08_198, out dx);
		si_104 &= ~0x02;
		wLoc0A = ax_108;
		wLoc08 = dx;
	}
	Eq_107 di_105 = 0x01;
	do
	{
		GlobalAlloc(si_104, dwArg06_347);
		byte ah_277 = SLICE(ax_353, byte, 8);
		if (ax_353 != 0x00)
			break;
		si_104 &= ~0x30;
		di_105 = di_354 - 0x01;
		ax_108 = di_354;
		ah_277 = SLICE(di_354, byte, 8);
		ax_353 = ax_108;
		di_354 = di_105;
	} while (di_354 != 0x00);
	word16 ax_137 = SEQ(ah_277, bArg04_219 & 0x04);
	if ((bArg04_219 & 0x04) != 0x00)
	{
		if (ax_353 != 0x00)
			GlobalPageLock(ax_353);
		ax_137 = fn0015_15CE(wLoc0A, wLoc08, out dx);
	}
	if (ax_353 == 0x00)
	{
		dxOut = 0x00;
		return 0x00;
	}
	else
	{
		GlobalLock(ax_353);
		dxOut = dx;
		return ax_137;
	}
}

// 0015:13CE: Register Eq_107 fn0015_13CE(Register Eq_107 ax, Stack Eq_107 wArg06)
// Called from:
//      fn0015_03C6
//      fn0015_0510
//      fn0015_1B9A
Eq_107 fn0015_13CE(Eq_107 ax, Eq_107 wArg06)
{
	GlobalHandle(wArg06);
	Eq_107 ax_17 = ds;
	if (ds == wArg06)
		ax_17.u0 = 0x00;
	if (ax == 0x00)
		return 0x00;
	GlobalFree(ax);
	return ax_17 < 0x01;
}

// 0015:1408: Register Eq_107 fn0015_1408(Register Eq_107 ax, Stack cui16 wArg04, Stack Eq_108 dwArg06, Stack Eq_107 wArg0C, Register out ptr16 dxOut)
// Called from:
//      fn0015_14F2
Eq_107 fn0015_1408(Eq_107 ax, cui16 wArg04, Eq_108 dwArg06, Eq_107 wArg0C, ptr16 & dxOut)
{
	byte bArg05 = SLICE(wArg04, byte, 8);
	word16 wArg08 = SLICE(dwArg06, word16, 16);
	cup16 wArg06 = (word16) dwArg06;
	byte bArg04 = (byte) wArg04;
	GlobalHandle(wArg0C);
	byte bLoc08_203 = 0x32;
	word16 wLoc0A_193 = 0x00;
	Eq_107 wLoc0C_194 = 0x01;
	Eq_108 dwArg06_374 = dwArg06;
	if ((bArg05 & 0x10) != 0x00)
	{
		if (wArg08 != 0x00)
		{
l0015_1438:
			dwArg06_374.u0 = 0xFFF0;
			goto l0015_1442;
		}
		dwArg06_374 = dwArg06;
		if (wArg06 > ~0x0F)
			goto l0015_1438;
	}
l0015_1442:
	cup16 wArg06_223 = (word16) dwArg06_374;
	word16 wArg08_219 = SLICE(dwArg06_374, word16, 16);
	if ((bArg05 & 0x01) != 0x00)
		bLoc08_203 = 114;
	uint16 wLoc08_237 = (uint16) bLoc08_203;
	if ((wArg04 & 0x0804) != 0x00)
		wLoc08_237 = (uint16) (bLoc08_203 & ~0x02);
	Eq_107 ax_115 = ax;
	if (ax == 0x00)
	{
l0015_14EC:
		int32 dx_ax_176 = (int32) ax_115;
		dxOut = SLICE(dx_ax_176, word16, 16);
		return (word16) dx_ax_176;
	}
	if ((bArg04 & 0x04) != 0x00)
		GlobalPageUnlock(ax);
	if (wArg08_219 != 0x00 || wArg06_223 > ~0x0F)
	{
		ax_115 = ds;
		if (ds == wArg0C)
			ax_115.u0 = 0x00;
		wLoc0A_193 = 0x01;
	}
	do
	{
		GlobalReAlloc(ax, dwArg06_374, wLoc08_237);
		byte bLoc08_241 = (byte) wLoc08_237;
		byte bLoc07_304 = SLICE(wLoc08_237, byte, 8);
		ax_115 = ax_380;
		if (ax_380 != 0x00)
			break;
		wLoc0C_194 = wLoc0C_381 - 0x01;
		ax_115 = wLoc0C_381;
		wLoc08_237 = SEQ(bLoc07_304, bLoc08_241 & ~0x30);
		ax_380 = ax_115;
		wLoc0C_381 = wLoc0C_194;
	} while (wLoc0C_381 != 0x00);
	if (wLoc0A_193 != 0x00)
	{
		if (ax_380 == 0x00)
		{
l0015_14C0:
			goto l0015_14C3;
		}
		ax_115 = ax;
		if (ax_380 == ax)
			goto l0015_14C0;
	}
l0015_14C3:
	if (ax_380 != 0x00 && (bArg04 & 0x04) != 0x00)
		GlobalPageLock(ax_380);
	if (ax_380 != 0x00)
	{
		GlobalLock(ax_380);
		dxOut = dx;
		return ax_115;
	}
	ax_115.u0 = 0x00;
	goto l0015_14EC;
}

// 0015:14F2: Register Eq_107 fn0015_14F2(Register Eq_107 ax, Stack Eq_107 wArg04, Stack Eq_108 dwArg06, Stack Eq_107 wArg0C)
// Called from:
//      fn0015_01B0
Eq_107 fn0015_14F2(Eq_107 ax, Eq_107 wArg04, Eq_108 dwArg06, Eq_107 wArg0C)
{
	word16 wArg08 = SLICE(dwArg06, word16, 16);
	cup16 wArg06 = (word16) dwArg06;
	byte ch_10 = SLICE(wArg04, byte, 8);
	byte cl_41 = (byte) wArg04;
	if ((ch_10 & 0x10) == 0x00 && (wArg08 != 0x00 || wArg06 > ~0x0F))
		return 0x00;
	cui16 dx_49;
	if ((dx_49 | fn0015_1408(ax, SEQ(ch_10 & ~0x02 | 0x08, cl_41), dwArg06, wArg0C, out dx_49)) == 0x00)
		return 0x00;
	return 0x01;
}

// 0015:1532: Register Eq_107 fn0015_1532(Register Eq_107 ax, Stack Eq_107 wArg06, Register out ptr16 dxOut)
// Called from:
//      fn0015_01B0
//      fn0015_03C6
//      fn0015_0510
//      fn0015_1902
Eq_107 fn0015_1532(Eq_107 ax, Eq_107 wArg06, ptr16 & dxOut)
{
	GlobalHandle(wArg06);
	if (ax == 0x00)
	{
		dxOut = 0x00;
		return 0x00;
	}
	else
	{
		GlobalSize(ax);
		dxOut = dx;
		return ax;
	}
}

// 0015:1558: Register Eq_108 fn0015_1558(Register Eq_108 ax, Register uint16 dx, Register out Eq_108 dxOut)
// Called from:
//      fn0015_131C
Eq_108 fn0015_1558(Eq_108 ax, uint16 dx, union Eq_108 & dxOut)
{
	Eq_108 ax_19 = 0x00;
	Eq_108 wLoc0C_100 = 0x00;
	if (dx <= 0x08)
	{
		uint32 dwLoc0A_130 = 0x00080000;
		if (dx >= 0x08)
		{
			dwLoc0A_130 = 0x00080000;
			if (ax != 0x00)
				goto l0015_15C4;
		}
		do
		{
			do
			{
				while (true)
				{
					GlobalDOSAlloc(dwLoc0A_130);
					Eq_108 wLoc0A_89 = (word16) dwLoc0A_130;
					cu16 wLoc08_87 = SLICE(dwLoc0A_130, word16, 16);
					if (ax_19 == 0x00)
						break;
					*ax_19 = 0x00;
					*((word32) ax_19 + 2) = wLoc0C_100;
					ax_19.u0 = 0x00;
					wLoc0C_100 = ax_19;
				}
				Eq_108 wLoc0A_96 = __rcr(wLoc0A_89, 0x01, SLICE(cond(wLoc08_87 >> 0x01), bool, 1));
				ax_19 = ax;
				dwLoc0A_130 = SEQ(wLoc08_87 >> 0x01, wLoc0A_96);
			} while (wLoc08_87 >> 0x01 > dx);
			if (wLoc08_87 >> 0x01 < dx)
				break;
			dwLoc0A_130 = SEQ(wLoc08_87 >> 0x01, wLoc0A_96);
		} while (wLoc0A_96 >= ax);
	}
l0015_15C4:
	dxOut = wLoc0C_100;
	return 0x00;
}

// 0015:15CE: Register Eq_107 fn0015_15CE(Stack Eq_107 wArg02, Stack (ptr16 Eq_756) wArg04, Register out (ptr16 Eq_756) dxOut)
// Called from:
//      fn0015_131C
Eq_107 fn0015_15CE(Eq_107 wArg02, struct Eq_756 * wArg04, struct Eq_756 & dxOut)
{
	Eq_107 ax_16 = wArg02;
	Eq_107 si_18 = wArg02;
	struct Eq_756 * wLoc08_59 = wArg04;
	struct Eq_756 * dx_20 = wArg04 | wArg02;
	if (dx_20 != 0x00)
	{
		do
		{
			Eq_107 ax_29 = wLoc08_59->*si_18;
			dx_20 = wLoc08_59->*((word32) si_18 + 2);
			GlobalDOSFree(wLoc08_59);
			si_18 = ax_29;
			wLoc08_59 = dx_20;
			ax_16 = dx_20 | ax_29;
		} while (ax_16 != 0x00);
	}
	dxOut = dx_20;
	return ax_16;
}

// 0015:160A: Register cui16 fn0015_160A(Register out Eq_2561 dxOut, Register out ptr16 siOut, Register out ptr16 diOut)
// Called from:
//      fn0015_167A
//      fn0015_179C
cui16 fn0015_160A(union Eq_2561 & dxOut, ptr16 & siOut, ptr16 & diOut)
{
	word16 ax_4 = fn0015_2146();
	if (ax_4 != 0x00)
	{
		if ((*((word16) ds + 24366) | *((word16) ds + 24364)) == 0x00)
		{
			*((word16) ds + 0x00005F30) = 0x01;
			*((word16) ds + 0x00005F32) = 0x01;
			ds.u0 = <invalid>;
			Eq_2561 dx_28;
			*((bool) ds.u0 + 24364) = fn0015_18EC(*((bool) ds.u0 + 0x00005F46), out dx_28, out si, out di);
			*((bool) ds.u0 + 24366) = dx_28;
			if ((dx_28 | *((bool) ds.u0 + 24364)) != 0x00)
			{
				if (*((bool) ds.u0 + 0x00005F42) != 0x00)
				{
					si = fn0015_1A54(*((bool) ds.u0 + 0x00005F42), SEQ(dx_28, *((bool) ds.u0 + 24364)), out di);
					ds.u0 = <invalid>;
				}
				if (*((bool) ds.u0 + 0x00005F44) != ~0x00)
				{
					fn0015_1AFE(*((bool) ds.u0 + 0x00005F44), SEQ(*((bool) ds.u0 + 24366), *((bool) ds.u0 + 24364)), out si, out di);
					ds.u0 = <invalid>;
				}
			}
		}
		fn0015_214A();
		cui16 ax_96 = *((word16) ds + 24364);
		dxOut = *((word16) ds + 24366);
		siOut = si;
		diOut = di;
		return ax_96;
	}
	else
	{
		int32 dx_ax_98 = (int32) ax_4;
		dxOut = SLICE(dx_ax_98, word16, 16);
		siOut = si;
		diOut = di;
		return (word16) dx_ax_98;
	}
}

// 0015:167A: Register cui16 fn0015_167A(Stack Eq_108 wArg04, Register out ptr16 dxOut, Register out ptr16 siOut, Register out ptr16 diOut)
// Called from:
//      fn0015_2950
cui16 fn0015_167A(Eq_108 wArg04, ptr16 & dxOut, ptr16 & siOut, ptr16 & diOut)
{
	if ((*((word16) ds + 24366) | *((word16) ds + 24364)) == 0x00)
	{
		ds.u0 = <invalid>;
		cui16 dx_16;
		ptr16 di_19;
		ptr16 si_22;
		if ((dx_16 | fn0015_160A(out dx_16, out si_22, out di_19)) == 0x00)
		{
			dxOut = 0x00;
			siOut = si_22;
			diOut = di_19;
			return 0x00;
		}
	}
	ptr16 di_51;
	ptr16 si_53;
	ptr16 dx_55;
	word16 cx_105;
	cui16 ax_54 = fn0015_0A48(0x00, wArg04, 0x00, SEQ(*((word16) ds + 24366), *((word16) ds + 24364)), out cx_105, out dx_55, out si_53, out di_51);
	dxOut = dx_55;
	siOut = si_53;
	diOut = di_51;
	return ax_54;
}

// 0015:1708: Register cui16 fn0015_1708(Stack Eq_108 wArg04, Stack cu16 wArg06, Stack cui16 wArg08, Stack Eq_1484 wArg0A, Stack cui16 wArg0C, Register out ptr16 cxOut, Register out Eq_2709 dxOut)
// Called from:
//      fn0015_179C
cui16 fn0015_1708(Eq_108 wArg04, cu16 wArg06, cui16 wArg08, Eq_1484 wArg0A, cui16 wArg0C, ptr16 & cxOut, union Eq_2709 & dxOut)
{
	struct Eq_2710 Eq_2734::* sp_118 = fp - 0x0A;
	if ((wArg06 | wArg04) == 0x00)
	{
		wArg04 = (word32) wArg04 + 1;
		wArg06 = (cu16) ((bool) (wArg04 < 0x01) + wArg06);
	}
	Eq_1484 si_112 = wArg0A;
	cui16 di_32 = wArg08;
	do
	{
		ptr16 cx_123;
		if ((wArg0C | si_112) != 0x00)
		{
			struct Eq_2731 Eq_2734::* sp_44 = sp_118 - 2;
			(ss->*sp_44).w0000 = wArg0C;
			(ss->*sp_44).tFFFFFFFE = si_112;
			(ss->*sp_44).wFFFFFFFC = wArg06;
			(ss->*sp_44).tFFFFFFFA = wArg04;
			(ss->*sp_44).wFFFFFFF8 = di_32;
			Eq_2709 dx_64;
			cui16 ax_63 = fn0015_0A48((ss->*sp_44).wFFFFFFF8, (ss->*sp_44).tFFFFFFFA, (ss->*sp_44).wFFFFFFFC, (ss->*sp_44).tFFFFFFFE, out cx, out dx_64, out si_112, out di_32);
			ds.u0 = <invalid>;
			if ((dx_64 | ax_63) != 0x00)
			{
				cxOut = cx;
				dxOut = dx_64;
				return ax_63;
			}
		}
		word16 ax_129;
		ptr16 cx_150;
		ptr16 cx_133;
		if ((di_32 & 0x8000) != 0x00 && (*((bool) ds.u0 + 0x00005F3A) | *((bool) ds.u0 + 0x00005F38)) != 0x00)
		{
			struct Eq_2789 Eq_2734::* sp_137 = sp_118 - 2;
			(ss->*sp_137).w0000 = 0x01;
			(ss->*sp_137).wFFFFFFFE = wArg06;
			(ss->*sp_137).tFFFFFFFC = wArg04;
			word16 sp_145;
			word16 bx_149;
			(*((bool) ds.u0 + 0x00005F38))();
			sp_118 = sp_145 + 0x06;
			cx = cx_150;
		}
		else
		{
			if ((*((bool) ds.u0 + 24374) | *((bool) ds.u0 + 24372)) == 0x00)
			{
				if ((*((bool) ds.u0 + 24382) | *((bool) ds.u0 + 0x00005F3C)) == 0x00)
					break;
				word16 bx_122;
				(*((bool) ds.u0 + 0x00005F3C))();
				cx = cx_123;
				continue;
			}
			(ss->*sp_118).wFFFFFFFE = wArg04;
			word16 sp_128;
			word16 bx_132;
			(*((bool) ds.u0 + 24372))();
			sp_118 = sp_128 + 0x02;
			cx = cx_133;
		}
	} while (ax_129 != 0x00);
	cxOut = cx;
	dxOut.u0 = 0x00;
	return 0x00;
}

// 0015:179C: Register word16 fn0015_179C(Stack Eq_108 wArg04)
// Called from:
//      fn0045_54AA
//      fn0045_60E8
word16 fn0015_179C(Eq_108 wArg04)
{
	Eq_1484 ax_16;
	cui16 dx_17;
	if ((ds->w5F2E | ds->t5F2C) != 0x00)
	{
		ax_16 = ds->t5F2C;
		dx_17 = ds->w5F2E;
	}
	else
	{
		word16 si_80;
		word16 di_81;
		ax_16 = fn0015_160A(out dx_17, out si_80, out di_81);
	}
	word16 dx_50;
	word16 cx_52;
	fn0015_1708(wArg04, 0x00, 0x00, ax_16, dx_17, out cx_52, out dx_50);
	return cx_52;
}

// 0015:18EC: Register Eq_108 fn0015_18EC(Stack word16 wArg04, Register out ptr16 dxOut, Register out ptr16 siOut, Register out ptr16 diOut)
// Called from:
//      fn0015_160A
Eq_108 fn0015_18EC(word16 wArg04, ptr16 & dxOut, ptr16 & siOut, ptr16 & diOut)
{
	ptr16 di_22;
	ptr16 si_25;
	ptr16 dx_26;
	Eq_108 ax_19 = fn0015_1902(wArg04, 0x00, 0x00, 0x0C, out dx_26, out si_25, out di_22);
	dxOut = dx_26;
	siOut = si_25;
	diOut = di_22;
	return ax_19;
}

// 0015:1902: Register Eq_108 fn0015_1902(Stack word16 wArg04, Stack uint16 wArg06, Stack uint16 wArg08, Stack Eq_107 wArg0A, Register out (ptr16 Eq_2878) dxOut, Register out ptr16 siOut, Register out ptr16 diOut)
// Called from:
//      fn0015_18EC
//      fn0045_54AA
Eq_108 fn0015_1902(word16 wArg04, uint16 wArg06, uint16 wArg08, Eq_107 wArg0A, struct Eq_2878 & dxOut, ptr16 & siOut, ptr16 & diOut)
{
	byte bArg05 = SLICE(wArg04, byte, 8);
	byte bArg04 = (byte) wArg04;
	struct Eq_2893 Eq_2923::* sp_13 = fp - 0x0A;
	word16 wArg04_316 = wArg04;
	if ((bArg05 & 0x80) != 0x00 && *((word16) (SLICE(cond(0x1E71), bool, 1) + 0x15) + 7793) != 0x9090)
		wArg04_316 = SEQ(bArg05, bArg04 | 0x01);
	if ((ds | 24346) != 0x00)
	{
		do
		{
			struct Eq_2919 Eq_2923::* sp_41 = sp_13 - 2;
			(ss->*sp_41).t0000.u0 = 0x00;
			(ss->*sp_41).tFFFFFFFE.u0 = 0x0100;
			byte ah_50 = SLICE(wArg04_316, byte, 8);
			(ss->*sp_41).tFFFFFFFC = SEQ(ah_50 | 0x10, (byte) wArg04_316 & ~0x04);
			struct Eq_2878 * dx_59;
			Eq_108 ax_57 = fn0015_131C(ah_50 | 0x10, (ss->*sp_41).tFFFFFFFC, (ss->*sp_41).tFFFFFFFE, out dx_59);
			sp_13 = (struct Eq_2893 Eq_2923::*) ((char *) &sp_41->t0000 + 2);
			if ((dx_59 | ax_57) != 0x00)
				break;
			(ss->*sp_41).t0000.u0 = 0x00;
			(ss->*sp_41).tFFFFFFFE.u0 = 0x00;
			(ss->*sp_41).tFFFFFFFC.u0 = 0x02;
			ds.u0 = <invalid>;
			sp_13 = (struct Eq_2893 Eq_2923::*) ((char *) &sp_41->t0000 + 0x0000FFF8);
			word16 cx_385;
			word16 di_386;
		} while (fn0015_1E61((ss->*sp_41).tFFFFFFFC, (ss->*sp_41).tFFFFFFFE, (ss->*sp_41).t0000, out cx_385, out di_386) != 0x00);
		if ((dx_59 | ax_57) != 0x00)
		{
			dx_59->*((word32) ax_57 + 46) = 24346;
			dx_59->*((word32) ax_57 + 48) = ds;
			struct Eq_2878 * dx_110 = *((bool) ds.u0 + 24352);
			dx_59->*((word32) ax_57 + 42) = *((bool) ds.u0 + 0x00005F1E);
			dx_59->*((word32) ax_57 + 44) = dx_110;
			*((bool) ds.u0 + 0x00005F1E) = ax_57;
			*((bool) ds.u0 + 24352) = dx_59;
			word16 cx_118;
			Eq_108 di_119 = ax_57;
			for (cx_118 = 0x05; cx_118 != 0x00; --cx_118)
			{
				dx_59->*di_119 = 0x00;
				di_119 = (word32) di_119 + 2;
			}
			dx_59->*((word32) ax_57 + 0x0A) = 0x00;
			dx_59->*((word32) ax_57 + 0x0E) = 0x00;
			dx_59->*((word32) ax_57 + 0x0C) = 0x00;
			dx_59->*((word32) ax_57 + 18) = 0x00;
			dx_59->*((word32) ax_57 + 16) = 0x00;
			dx_59->*((word32) ax_57 + 20) = 48813;
			Eq_107 ax_140 = SEQ(SLICE(wArg04_316, byte, 8), (byte) wArg04_316 & ~0x02);
			dx_59->*((word32) ax_57 + 22) = ax_140;
			dx_59->*((word32) ax_57 + 24) = 0x00;
			dx_59->*((word32) ax_57 + 26) = 0x2000;
			dx_59->*((word32) ax_57 + 28) = 0x0800;
			struct Eq_3073 Eq_2923::* sp_146 = sp_13 - 2;
			(ss->*sp_146).w0000 = dx_59;
			(ss->*sp_146).tFFFFFFFE = ax_57;
			word16 dx_151;
			dx_59->*((word32) ax_57 + 30) = fn0015_1532(ax_140, (ss->*sp_146).w0000, out dx_151);
			dx_59->*((word32) ax_57 + 32) = dx_151;
			dx_59->*((word32) ax_57 + 36) = 0x00;
			dx_59->*((word32) ax_57 + 0x0022) = 0x00;
			dx_59->*((word32) ax_57 + 38) = ~0x01;
			dx_59->*((word32) ax_57 + 40) = ~0x00;
			dx_59->*((word32) ax_57 + 50) = 0x00;
			dx_59->*((word32) ax_57 + 52) = 0x00;
			dx_59->*((word32) ax_57 + 64) = 0x00;
			dx_59->*((word32) ax_57 + 62) = 0x00;
			(ss->*sp_146).w0000 = dx_59;
			(ss->*sp_146).tFFFFFFFE = ax_57;
			(ss->*sp_146).tFFFFFFFC = wArg0A;
			uint16 di_180;
			Eq_108 si_184;
			Eq_107 ax_177 = fn0015_1AFE((ss->*sp_146).tFFFFFFFC, (ss->*sp_146).tFFFFFFFE, out si_184, out di_180);
			if (ax_177 != 0x00)
			{
				if ((wArg08 | wArg06) != 0x00)
				{
					(ss->*sp_146).w0000 = dx_59;
					(ss->*sp_146).tFFFFFFFE = si_184;
					(ss->*sp_146).tFFFFFFFC.u0 = 0x00;
					(ss->*sp_146).wFFFFFFFA = di_180;
					(ss->*sp_146).wFFFFFFF8 = wArg08;
					(ss->*sp_146).wFFFFFFF6 = wArg06;
					Eq_107 dx_216;
					uint16 ax_214 = fn0015_52BE((ss->*sp_146).wFFFFFFF6, (ss->*sp_146).wFFFFFFF8, (ss->*sp_146).wFFFFFFFA, (ss->*sp_146).tFFFFFFFC, out dx_216);
					(ss->*sp_146).tFFFFFFFC = dx_216;
					(ss->*sp_146).wFFFFFFFA = ax_214;
					(ss->*sp_146).wFFFFFFF8 = 0x01;
					fn0015_010C((ss->*sp_146).wFFFFFFF8, (ss->*sp_146).wFFFFFFFA, (ss->*sp_146).tFFFFFFFC, (ss->*sp_146).tFFFFFFFE);
				}
				ptr16 si_247 = (ss->*sp_13).w0000;
				ptr16 di_249 = sp_13[1];
				dxOut = dx_59;
				siOut = si_247;
				diOut = di_249;
				return si_184;
			}
			(ss->*sp_146).w0000 = dx_59;
			(ss->*sp_146).tFFFFFFFE = si_184;
			(ss->*sp_146).tFFFFFFFC = ax_177;
			fn0015_1B9A(ax_177, (ss->*sp_146).tFFFFFFFE);
			sp_13 = (struct Eq_2893 Eq_2923::*) (sp_146 + 1);
		}
	}
	ptr16 si_287 = (ss->*sp_13).w0000;
	ptr16 di_289 = sp_13[1];
	dxOut = 0x00;
	siOut = si_287;
	diOut = di_289;
	return 0x00;
}

// 0015:1A54: Register word16 fn0015_1A54(Stack uint16 wArg04, Stack (ptr32 Eq_2631) dwArg06, Register out ptr16 diOut)
// Called from:
//      fn0015_160A
word16 fn0015_1A54(uint16 wArg04, struct Eq_2631 * dwArg06, ptr16 & diOut)
{
	if (dwArg06->w0014 == 48813)
	{
		cu16 ax_21 = fn0015_1AB0(wArg04);
		if (dwArg06->w0018 + 0x14 <= ax_21)
		{
			dwArg06->w001A = ax_21;
			dwArg06->w001C = ax_21 >> 0x02;
		}
		diOut = di;
		return si;
	}
	else
	{
		word16 di_135;
		word16 cx_134;
		fn0015_1E61(0x0A, 0x00, 0x00, out cx_134, out di_135);
		diOut = wLoc0E;
		return wLoc10;
	}
}

// 0015:1AB0: Register uint16 fn0015_1AB0(Register uint16 ax)
// Called from:
//      fn0015_1A54
uint16 fn0015_1AB0(uint16 ax)
{
	if (ax == 0x2000)
		return ax;
	if (ax >= ~0x0F)
		return ~0x0F;
	if (ax <= 0x1000)
		return 0x1000;
	uint16 si_19 = 0x2000;
	if (ax <= 0x2000)
	{
		do
			si_19 >>= 0x01;
		while (si_19 >= ax);
		ax = si_19 * 0x02;
		return ax;
	}
	else
	{
		do
		{
			si_19 *= 0x02;
			if (si_19 == 0x00)
				return ~0x0F;
		} while (si_19 < ax);
		return (si_19 - ~0x0F & 0x00 - (si_19 < ~0x0F)) + ~0x0F;
	}
}

// 0015:1AFE: Register word16 fn0015_1AFE(Stack Eq_107 wArg04, Stack Eq_108 ptrArg06, Register out ptr16 siOut, Register out ptr16 diOut)
// Called from:
//      fn0015_160A
//      fn0015_1902
word16 fn0015_1AFE(Eq_107 wArg04, Eq_108 ptrArg06, ptr16 & siOut, ptr16 & diOut)
{
	Eq_107 cx_20;
	struct Eq_3327 Eq_3391::* sp_12 = fp - 6;
	if (wArg04 != 0x00)
		cx_20 = SEQ(SLICE((word32) wArg04 + 1, byte, 8), (byte) ((word32) wArg04 + 1) & ~0x01);
	else
		cx_20.u0 = 0x00;
	Eq_107 es_32 = SLICE(ptrArg06, selector, 16);
	Eq_108 si_33 = (word16) ptrArg06;
	if (*((word32) ptrArg06 + 20) != 48813)
	{
		word16 cx_190;
		word16 di_191;
		fn0015_1E61(0x0A, 0x00, 0x00, out cx_190, out di_191);
		siOut = wLoc10;
		diOut = wLoc0E;
		return 0x00;
	}
	word16 si_75;
	if (cx_20 >= wArg04 && *((word32) ptrArg06 + 26) - 0x14 >= cx_20)
	{
		if (*((word32) ptrArg06 + 2) == 0x00)
		{
			*((word32) ptrArg06 + 24) = cx_20;
			si_75 = 0x01;
l0015_1B5F:
			ptr16 di_90 = (ss->*sp_12).ptr0002;
			siOut = (ss->*sp_12).ptr0000;
			diOut = di_90;
			return si_75;
		}
	}
	else
	{
		word16 di_193;
		word16 cx_192;
		fn0015_1E61(0x03, si_33, es_32, out cx_192, out di_193);
		sp_12 = fp - 0x10;
	}
	si_75 = 0x00;
	goto l0015_1B5F;
}

// 0015:1B68: Register Eq_107 fn0015_1B68(Register Eq_107 ax, Stack Eq_108 dwArg04)
// Called from:
//      fn0045_54AA
Eq_107 fn0015_1B68(Eq_107 ax, Eq_108 dwArg04)
{
	if (*((word32) dwArg04 + 20) == 48813)
		return fn0015_1B9A(ax, dwArg04);
	word16 cx_96;
	word16 di_97;
	fn0015_1E61(0x0A, 0x00, 0x00, out cx_96, out di_97);
	return 0x00;
}

// 0015:1B9A: Register Eq_107 fn0015_1B9A(Register Eq_107 ax, Stack Eq_108 ptrArg06)
// Called from:
//      fn0015_1902
//      fn0015_1B68
Eq_107 fn0015_1B9A(Eq_107 ax, Eq_108 ptrArg06)
{
	Eq_107 psegArg08_153 = SLICE(ptrArg06, selector, 16);
	*((word32) ptrArg06 + 20) = 0x00;
	Eq_107 ds_145 = psegArg08_153;
	uint16 wLoc04_154 = 0x00;
	do
	{
		word16 si_28 = SEQ(ds_145, 0x00)[wLoc04_154 * 0x02];
		struct Eq_3432 * ds_si_194 = SEQ(ds_145, si_28);
		if (si_28 != 0x00)
		{
			do
			{
				ds_si_194->ptr0008->w000C = 0x00;
				ax = fn0015_13CE(ax, ds_si_194->t000A);
				ds_145.u0 = <invalid>;
				word16 si_56 = (ds_145->*(word16) ds_si_194).w0004;
				ds_si_194 = SEQ(ds_145, si_56);
			} while (SEQ(ds_145, 0x00)[wLoc04_154 * 0x02] != si_56);
		}
		uint16 v16_65 = wLoc04_154 + 0x01;
		wLoc04_154 = v16_65;
	} while (v16_65 < 0x05);
	struct Eq_3465 * dx_ax_197 = SEQ(*((word32) ptrArg06 + 18), *((word32) ptrArg06 + 16));
	while (true)
	{
		Eq_107 dx_82 = SLICE(dx_ax_197, word16, 16);
		if ((dx_82 | (word16) dx_ax_197) == 0x00)
			break;
		Eq_107 ax_128 = dx_ax_197->t0000;
		word16 dx_129 = dx_ax_197->w0002;
		fn0015_13CE(ax_128, dx_82);
		dx_ax_197 = SEQ(dx_129, ax_128);
	}
	fn0015_13CE(fn0015_20A2(ptrArg06), psegArg08_153);
	return 0x01;
}

// 0015:1DFA: Register word16 fn0015_1DFA(Register byte ah, Stack Eq_3499 wArg02, Stack byte bArg04, Stack uint16 wArg06, Stack int16 wArg08, Register out Eq_3499 cxOut)
// Called from:
//      fn0015_21B6
word16 fn0015_1DFA(byte ah, Eq_3499 wArg02, byte bArg04, uint16 wArg06, int16 wArg08, union Eq_3499 & cxOut)
{
	cui16 ax_34;
	cui16 ax_11 = SEQ(ah, bArg04);
	cui16 cx_15 = 0x00 - ((ax_11 & 0x04) < 0x01);
	byte ah_24 = SLICE(ax_11 & 0x04, byte, 8);
	Eq_3499 cx_100 = SEQ(SLICE(cx_15 & 0x8200, byte, 8) + 0x18, (byte) (cx_15 & 0x8200));
	if ((ax_11 & 0x04) != 0x00)
		ax_34 = 0x1800;
	else
	{
		cui16 ax_29 = 0x00 - ((SEQ(ah_24, bArg04) & 0x02) < 0x01);
		ax_34 = SEQ(SLICE(ax_29 & 0xFE00, byte, 8) + 0x92, (byte) (ax_29 & 0xFE00));
	}
	if (wArg08 != 0x00)
	{
		cui16 ax_47 = __lar(wArg08);
		if (Test(EQ,true) && (ax_47 & cx_100) == ax_34)
		{
			cx_100 = wArg02;
			if (wArg02 == 0x00)
			{
l0015_1E52:
				cxOut = cx_100;
				return 0x00;
			}
			cup16 ax_56 = __lsl(wArg08);
			cx_100 = wArg02 - 0x01;
			cup16 bx_59 = wArg06 + (wArg02 - 0x01);
			if (bx_59 >= 0x00 && ax_56 >= bx_59)
				goto l0015_1E52;
		}
	}
	cxOut = cx_100;
	return 0x01;
}

// 0015:1E61: Register word16 fn0015_1E61(Stack Eq_107 wArg04, Stack Eq_108 wArg06, Stack Eq_107 wArg08, Register out ptr16 cxOut, Register out ptr16 diOut)
// Called from:
//      fn0015_010C
//      fn0015_01B0
//      fn0015_03C6
//      fn0015_05E2
//      fn0015_0838
//      fn0015_0A48
//      fn0015_1902
//      fn0015_1A54
//      fn0015_1AFE
//      fn0015_1B68
word16 fn0015_1E61(Eq_107 wArg04, Eq_108 wArg06, Eq_107 wArg08, ptr16 & cxOut, ptr16 & diOut)
{
	0015->w1E71 != 0x9090;
	ptr16 cx_15;
	ptr16 di_16;
	word16 ax_20 = SHI_INVOKEERRORHANDLER1(wArg04, wArg06, wArg08, out cx_15, out di_16);
	cxOut = cx_15;
	diOut = di_16;
	return ax_20;
}

// 0015:1E70: Register word16 SHI_INVOKEERRORHANDLER1(Stack Eq_107 wArg04, Stack Eq_108 wArg06, Stack Eq_107 wArg08, Register out Eq_3587 cxOut, Register out ptr16 diOut)
// Called from:
//      fn0015_1E61
word16 SHI_INVOKEERRORHANDLER1(Eq_107 wArg04, Eq_108 wArg06, Eq_107 wArg08, union Eq_3587 & cxOut, ptr16 & diOut)
{
	Eq_3587 cx_214 = ds | 24346;
	if ((ds | 24346) != 0x00)
	{
		<anonymous> * dx_ax_247;
		cui16 ax_34 = ds->w5F1C | ds->w5F1A;
		byte ah_48 = SLICE(ax_34, byte, 8);
		if (ax_34 != 0x00)
		{
			if (fn0015_21B6(ah_48, ds->w5F1A, ds->w5F1C, out cx_214) != 0x00)
				dx_ax_247 = SEQ(ds->w5F1C, ds->w5F1A);
			else
			{
				ds->w5F1A = 0x1F7E;
				ds->w5F1C = 0x15;
				dx_ax_247 = 1384318;
			}
		}
		else
			dx_ax_247 = null;
		cui16 dx_71 = SLICE(dx_ax_247, word16, 16);
		cui16 ax_68 = (word16) dx_ax_247;
		if ((dx_71 | ax_68) != 0x00)
		{
			word16 di_118;
			struct Eq_3647 Eq_3674::* sp_111 = fp - 0x44;
			cui16 wLoc04_191 = dx_71;
			cui16 wLoc06_192 = ax_68;
			Eq_3587 cx_115;
			if (fn0015_1F24(0x00, &ds->w5F1A, out cx_115) != 0x00)
			{
				wLoc04_191 = 0x00;
				wLoc06_192 = 0x00;
				di_118 = 0x00;
			}
			else
			{
				word16 ax_112;
				dx_ax_247();
				di_118 = ax_112;
			}
			if ((wLoc04_191 | wLoc06_192) != 0x00)
				cx_115 = fn0015_1F68();
			ptr16 di_149 = (ss->*sp_111).ptr0002;
			cxOut = cx_115;
			diOut = di_149;
			return di_118;
		}
	}
	cxOut = cx_214;
	diOut = di;
	return 0x00;
}

// 0015:1F24: Register wchar_t fn0015_1F24(Register wchar_t ax, Stack (ptr32 Eq_3657) dwArg02, Register out Eq_107 cxOut)
// Called from:
//      SHI_INVOKEERRORHANDLER1
wchar_t fn0015_1F24(wchar_t ax, struct Eq_3657 * dwArg02, union Eq_107 & cxOut)
{
	wchar_t si_21 = dwArg02->w000C;
	if (si_21 <= ax)
		++dwArg02->w000C;
	if (si_21 > ax)
		fn0015_214C(ax, 0x00, 0x038DD940);
	if (si_21 <= ax)
	{
		cxOut.u0 = <invalid>;
		return 0x00;
	}
	else
	{
		cxOut.u0 = <invalid>;
		return 0x01;
	}
}

// 0015:1F68: Register cui16 fn0015_1F68()
// Called from:
//      SHI_INVOKEERRORHANDLER1
cui16 fn0015_1F68()
{
	if ((ds | 24346) != 0x00)
	{
		ci16 v9_12 = ds->w5F26 - 0x01;
		ds->w5F26 = v9_12;
		if (v9_12 < 0x00)
			ds->w5F26 = 0x00;
	}
	return ds | 24346;
}

// 0015:1FEA: void fn0015_1FEA()
// Called from:
//      fn0045_54AA
void fn0015_1FEA()
{
	if ((ds | 24346) != 0x00)
	{
		word16 ax_12 = ds->w5F22;
		++ds->w5F22;
		if (ax_12 == 0x00 && (ds->w5F20 | ds->w5F1E) != 0x00)
			++ds->w5F22;
	}
	if ((ds | 24346) == 0x00)
		;
}

// 0015:20A2: Register Eq_3752 fn0015_20A2(Stack Eq_108 dwArg04)
// Called from:
//      fn0015_1B9A
Eq_3752 fn0015_20A2(Eq_108 dwArg04)
{
	Eq_3752 wArg04 = (word16) dwArg04;
	struct Eq_3755 * psegArg06 = SLICE(dwArg04, selector, 16);
	struct Eq_3757 Eq_3761::* ax_19 = *((word32) dwArg04 + 46);
	struct Eq_3761 * dx_20 = *((word32) dwArg04 + 48);
	Eq_3752 ax_135 = (dx_20->*ax_19).t0004;
	struct Eq_3755 * dx_30 = (dx_20->*ax_19).ptr0006;
	Eq_3752 di_25 = 0x00;
	struct Eq_3755 * wLoc08_114 = 0x00;
	Eq_3752 bx_31 = ax_135;
	struct Eq_3755 * wLoc04_115 = dx_30;
	struct Eq_3779 * ptrLoc0E_132 = ax_19;
	if ((dx_30 | ax_135) == 0x00)
		return ax_135;
	do
	{
		if (bx_31 == wArg04 && wLoc04_115 == psegArg06)
		{
			if ((wLoc08_114 | di_25) == 0x00)
			{
				ax_135 = wLoc04_115->*((word16) bx_31 + 42);
				struct Eq_3755 * dx_55 = wLoc04_115->*((word16) bx_31 + 44);
				ptrLoc0E_132->t0004 = ax_135;
				ptrLoc0E_132->ptr0006 = dx_55;
				return ax_135;
			}
			else
			{
				Eq_3752 ax_73 = wLoc04_115->*((word16) bx_31 + 42);
				struct Eq_3755 * dx_74 = wLoc04_115->*((word16) bx_31 + 44);
				wLoc08_114->*((word16) di_25 + 42) = ax_73;
				wLoc08_114->*((word16) di_25 + 44) = dx_74;
				return ax_73;
			}
		}
		Eq_3752 ax_91 = wLoc04_115->*((word16) bx_31 + 42);
		struct Eq_3755 * dx_92 = wLoc04_115->*((word16) bx_31 + 44);
		di_25 = bx_31;
		wLoc08_114 = wLoc04_115;
		bx_31 = ax_91;
		wLoc04_115 = dx_92;
	} while ((dx_92 | ax_91) != 0x00);
	return ax_91;
}

// 0015:2146: Register word16 fn0015_2146()
// Called from:
//      fn0015_160A
word16 fn0015_2146()
{
	return 0x01;
}

// 0015:214A: void fn0015_214A()
// Called from:
//      fn0015_160A
void fn0015_214A()
{
}

// 0015:214C: void fn0015_214C(Register wchar_t ax, Stack cup16 wArg06, Stack (ptr32 char) dwArg08)
// Called from:
//      fn0015_1F24
void fn0015_214C(wchar_t ax, cup16 wArg06, char * dwArg08)
{
	MessageBeep(0x00);
	cui16 si_19 = 0x00 - (wArg06 < 0x01) + 0x02 | 0x2110;
	while (true)
	{
		MessageBox(0x00, dwArg08, 0x00151DE8<p32>, si_19);
		ci16 ax_46 = ax - 0x01;
		if (ax_46 == 0x00)
			break;
		ax = ax_46 - 0x01;
		if (ax_46 >= 0x01 && !OVERFLOW(ax_46 - 0x01))
		{
			if (ax_46 <= 0x02)
			{
				fn0015_3E9E();
				return;
			}
			if (ax_46 == 0x03)
				return;
			ax = ax_46 - 0x04;
			if (ax_46 == 0x04)
				return;
		}
		if ((si_19 & 0x2000) == 0x00)
			return;
		si_19 = si_19 & ~0x2010 | 0x1010;
	}
}

// 0015:21B6: Register Eq_3883 fn0015_21B6(Register byte ah, Stack uint16 wArg04, Stack int16 wArg06, Register out Eq_3618 cxOut)
// Called from:
//      SHI_INVOKEERRORHANDLER1
Eq_3883 fn0015_21B6(byte ah, uint16 wArg04, int16 wArg06, union Eq_3618 & cxOut)
{
	Eq_3618 cx_22;
	Eq_3883 ax_31 = fn0015_1DFA(ah, 0x00, 0x04, wArg04, wArg06, out cx_22) < 0x01;
	cxOut = cx_22;
	return ax_31;
}

// 0015:2300: void fn0015_2300(Register word16 ax, Register word16 cx, Register word16 dx, Register word16 bx, Register word16 si, Register word16 di, Register (ptr16 Eq_3900) es, Stack Eq_107 wArg04)
void fn0015_2300(word16 ax, word16 cx, word16 dx, word16 bx, word16 si, word16 di, struct Eq_3900 * es, Eq_107 wArg04)
{
	struct Eq_3902 Eq_3908::* sp_180 = fp;
	while (true)
	{
		struct Eq_3904 Eq_3908::* sp_6 = sp_180 - 2;
		(ss->*sp_6).t0000.u0 = 0x00;
		InitTask();
		byte ah_181 = SLICE(ax, byte, 8);
		if (ax != 0x00)
		{
			*((bool) ds.u0 + 24446) = es;
			cup16 cx_18 = cx + 0x0100;
			if (cx_18 >= 0x00)
			{
				*((bool) ds.u0 + 24392) = cx_18;
				*((bool) ds.u0 + 24394) = si;
				*((bool) ds.u0 + 0x00005F4C) = di;
				*((bool) ds.u0 + 0x00005F4E) = bx;
				*((bool) ds.u0 + 0x00005F50) = es;
				*((bool) ds.u0 + 0x00005F52) = dx;
				(ss->*sp_6).wFFFFFFFE = ~0x00;
				LockSegment((ss->*sp_6).wFFFFFFFE);
				GetVersion();
				*((bool) ds.u0 + 24448) = ~0x00;
				if ((0015->w22F6 & 0x01) != 0x00)
					DOS3Call();
				else
					__syscall(33);
				*((bool) ds.u0 + 24452) = 0x30FF;
				*((bool) ds.u0 + 24450) = ~0xCF;
				if ((0015->w22F6 & 0x01) == 0x00)
					*((bool) ds.u0 + 24455) = 0x00;
				(ss->*sp_6).wFFFFFFFE = 0x00;
				WaitEvent((ss->*sp_6).wFFFFFFFE);
				(ss->*sp_6).wFFFFFFFE = *((bool) ds.u0 + 0x00005F4C);
				InitApp((ss->*sp_6).wFFFFFFFE);
				ah_181 = 0x00;
				if (false)
				{
					word16 bp_227;
					Eq_107 es_91;
					word16 dx_118;
					word16 cx_115 = fn0015_27D6(fn0015_262C(fn0015_23EA(bx, 0x00, es, (ss->*sp_6).tFFFFFFFC, (ss->*sp_6).t0000, out es_91), es_91, (ss->*sp_6).t0000, (ss->*sp_6).w0002), out dx_118, out bp_227);
					fn0015_55AC();
					Eq_107 ax_155 = (word16) (uint32) fn0015_23BE(cx_115, dx_118);
					fn0015_24CD();
					word16 dx_228;
					struct Eq_4085 * es_229;
					fn0015_289A(ax_155, wArg04, out dx_228, out es_229);
					return;
				}
			}
		}
		(ss->*sp_6).wFFFFFFFE = SEQ(ah_181, ~0x00);
		sp_180 = sp_6 - 2;
		ax = fn0015_24DB(out cx, out dx, out si, out di);
		ds.u0 = <invalid>;
	}
}

// 0015:23BE: Register word16 fn0015_23BE(Register word16 cx, Register word16 dx)
// Called from:
//      fn0015_2300
word16 fn0015_23BE(word16 cx, word16 dx)
{
	return (word16) (uint32) fn0045_54AA(cx, dx, ds->w5F52, SEQ(ds->w5F50, ds->w5F4E), ds->w5F4A, ds->w5F4C);
}

// 0015:23EA: Register mp16 fn0015_23EA(Register word16 bx, Register mp16 bp, Register (ptr16 Eq_3900) es, Stack Eq_107 wArg00, Stack Eq_107 wArg04, Register out (ptr16 Eq_4050) esOut)
// Called from:
//      fn0015_2300
mp16 fn0015_23EA(word16 bx, mp16 bp, struct Eq_3900 * es, Eq_107 wArg00, Eq_107 wArg04, struct Eq_4050 & esOut)
{
	if ((0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
		__syscall(33);
	ds->w5F6A = bx;
	ds->ptr5F6C = es;
	mp16 sp_239 = fp - 4;
	if ((0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
		__syscall(33);
	struct Eq_4050 * ax_39 = fn0015_29DC();
	if (ax_39->w6202 != 0x00)
	{
		byte SCZO_67;
		ax_39->ptr6200();
		if (!SLICE(SCZO_67, bool, 1))
		{
			word16 dx_373;
			struct Eq_4050 * es_232;
			fn0015_289A(wArg00, wArg04, out dx_373, out es_232);
			esOut = es_232;
			return fp - 2;
		}
		ax_39->ptr6200();
	}
	struct Eq_4050 * es_119 = ax_39->ptr5F7E;
	struct Eq_4050 * cx_82 = es_119->ptr002C;
	if (cx_82 != 0x00)
	{
		es_119 = cx_82;
		byte Eq_4050::* di_102 = &Eq_4050::b0000;
		do
		{
			bool v26_261 = cx_82->*di_102 == 0x00;
			if (cx_82->*di_102 == 0x00)
				break;
			word16 cx_103 = 0x0D;
			byte Eq_4050::* si_101 = &Eq_4050::b5F5C;
			while (cx_103 != 0x00)
			{
				v26_261 = ax_39->*si_374 == cx_82->*di_102;
				si_101 = si_374 + 1;
				++di_102;
				--cx_103;
				si_374 = si_101;
				if (ax_39->*si_374 == cx_82->*di_102)
					break;
			}
			if (v26_261)
			{
				struct Eq_4217 Eq_4220::* sp_110 = sp_239 - 2;
				(ss->*sp_110).ptr0000 = cx_82;
				(ss->*sp_110).ptrFFFFFFFE = ax_39;
				es_119 = (ss->*sp_110).ptrFFFFFFFE;
				struct Eq_4050 * ds_121 = (ss->*sp_110).ptr0000;
				byte Eq_4050::* si_124 = di_102;
				byte Eq_4050::* di_125 = Eq_4050::a5F90;
				while (true)
				{
					cu8 al_130 = ds_121->*si_124;
					byte Eq_4050::* si_131 = si_124 + 1;
					if (al_130 < 0x41)
						break;
					ui8 al_136 = al_130 - 0x41 << 0x04;
					cu8 al_143 = ds_121->*si_131;
					si_124 = si_131 + 1;
					if (al_143 < 0x41)
						break;
					es_119->*di_125 = al_143 - 0x41 | al_136;
					++di_125;
				}
				(ss->*sp_110).ptr0000 = es_119;
				break;
			}
			word16 cx_165 = 0x7FFF;
			bool v30_265 = false;
			while (cx_165 != 0x00)
			{
				v30_265 = cx_82->*di_102 != 0x00;
				++di_102;
				--cx_165;
				if (cx_82->*di_102 != 0x00)
					break;
			}
		} while (!v30_265);
	}
	fn0015_2594(0x620C, 0x620C);
	fn0015_2594(0x620C, 0x620C);
	fn0015_2594(0x61EE, 0x61FE);
	esOut = es_119;
	return bp;
}

// 0015:24CD: Register word16 fn0015_24CD()
// Called from:
//      fn0015_2300
word16 fn0015_24CD()
{
	word16 bp_20;
	word16 cx_33;
	word16 dx_34;
	word16 si_35;
	word16 di_36;
	fn0015_250A(fp - 2, 0x00, out cx_33, out dx_34, out bp_20, out si_35, out di_36);
	return bp_20;
}

// 0015:24DB: Register word16 fn0015_24DB(Register out ptr16 cxOut, Register out ptr16 dxOut, Register out ptr16 siOut, Register out ptr16 diOut)
// Called from:
//      fn0015_2300
word16 fn0015_24DB(ptr16 & cxOut, ptr16 & dxOut, ptr16 & siOut, ptr16 & diOut)
{
	ptr16 cx_20;
	ptr16 di_21;
	ptr16 dx_23;
	ptr16 si_24;
	word16 bp_36;
	word16 ax_18 = fn0015_250A(fp - 2, 0x01, out cx_20, out dx_23, out bp_36, out si_24, out di_21);
	cxOut = cx_20;
	dxOut = dx_23;
	siOut = si_24;
	diOut = di_21;
	return ax_18;
}

// 0015:250A: Register word16 fn0015_250A(Sequence (ptr32 Eq_4313) ss_bp, Register word16 cx, Register out ptr16 cxOut, Register out ptr16 dxOut, Register out ptr16 bpOut, Register out ptr16 siOut, Register out ptr16 diOut)
// Called from:
//      fn0015_24CD
//      fn0015_24DB
word16 fn0015_250A(struct Eq_4313 * ss_bp, word16 cx, ptr16 & cxOut, ptr16 & dxOut, ptr16 & bpOut, ptr16 & siOut, ptr16 & diOut)
{
	byte ch = SLICE(cx, byte, 8);
	byte cl = (byte) cx;
	ds->b5FC9 = ch;
	if (cl == 0x00)
	{
		fn0015_2594(0x68B6, 0x68B6);
		fn0015_2594(0x620C, 0x6210);
		fn0015_55AC();
	}
	fn0015_2594(0x6210, 0x6210);
	fn0015_2594(0x6210, 0x6210);
	fn0015_256B();
	word16 ax_95 = cx;
	if (ch == 0x00)
	{
		ax_95 = SEQ(0x4C, ss_bp->b0006);
		if ((0015->w22F6 & 0x01) != 0x00)
			DOS3Call();
		else
			__syscall(33);
	}
	ptr16 bp_84 = ss_bp->w0000 - 0x01;
	cxOut = cx_48;
	dxOut = dx_49;
	bpOut = bp_84;
	siOut = wArg02;
	diOut = wArg00;
	return ax_95;
}

// 0015:256B: void fn0015_256B()
// Called from:
//      fn0015_24DB
void fn0015_256B()
{
	if (ds->w6202 != 0x00)
		ds->ptr6200();
	if ((0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
		__syscall(33);
}

// 0015:2594: void fn0015_2594(Register Eq_4174 si, Register Eq_4174 di)
// Called from:
//      fn0015_23EA
//      fn0015_24DB
void fn0015_2594(Eq_4174 si, Eq_4174 di)
{
	while (si < di)
	{
		di -= 0x04;
		if ((ds->*di | ds->*((word16) di + 2)) != 0x00)
		{
			word16 ax_19;
			(ds->*di)();
		}
	}
}

// 0015:25A8: void fn0015_25A8()
// Called from:
//      fn0015_289A
void fn0015_25A8()
{
	fn0015_2913(252);
	fn0015_2913(0xFF);
}

// 0015:262C: Register word16 fn0015_262C(Register Eq_4039 bp, Register Eq_107 es, Stack Eq_107 wArg00, Stack word16 wArg02)
// Called from:
//      fn0015_2300
word16 fn0015_262C(Eq_4039 bp, Eq_107 es, Eq_107 wArg00, word16 wArg02)
{
	ds->t5FD2 = wArg00;
	ds->w5FD4 = wArg02;
	Eq_107 dx_21;
	word16 di_581;
	struct Eq_4463 * es_582;
	word16 bp_579;
	word16 si_580;
	Eq_4466 ax_15 = fn0015_2950(0x0104, bp, es, out dx_21, out bp_579, out si_580, out di_581, out es_582);
	Eq_107 ds_20 = <invalid>;
	*((word32) ds_20 + 0x00005FC4) = dx_21;
	*((word32) ds_20 + 24514) = ax_15;
	Eq_107 sp_24 = <invalid>;
	ss->*((word32) sp_24 - 4) = dx_21;
	ss->*((word32) sp_24 - 6) = ax_15;
	ss->*((word32) sp_24 - 8) = *((word32) ds_20 + 0x00005F4C);
	ss->*((word32) sp_24 - 0x0A) = dx_21;
	ss->*((word32) sp_24 - 0x0C) = ax_15;
	ss->*((word32) sp_24 - 0x0E) = 0x0104;
	GetModuleFileName(ss->*((word32) sp_24 - 8), ss->*((word32) sp_24 - 0x0C), ss->*((word32) sp_24 - 0x0E));
	(sp_24 - 0x04)->*((word32) (ss->*((word32) sp_24 - 6)) + 260) = 0x00;
	ss->*((word32) sp_24 - 4) = ds_20;
	word16 dx_120 = 0x01;
	Eq_107 es_57 = ss->*((word32) sp_24 - 4);
	word16 di_154 = 0x01;
	byte Eq_3900::* si_108 = &Eq_3900::b0081;
	struct Eq_3900 * ds_61 = *((word32) ds_20 + 24446);
	while (true)
	{
		do
		{
			byte al_65 = ds_61->*si_108;
			++si_108;
		} while (al_65 == 0x20 || al_65 == 0x09);
		if (al_65 == 0x0D || al_65 == 0x00)
			break;
		++di_154;
l0015_267E:
		--si_108;
		while (true)
		{
l0015_267F:
			byte al_86 = ds_61->*si_108;
			++si_108;
			if (al_86 == 0x20 || al_86 == 0x09)
				break;
			if (al_86 == 0x0D || al_86 == 0x00)
				goto l0015_26E8;
			if (al_86 == 0x22)
			{
l0015_26B8:
				while (true)
				{
					byte al_130 = ds_61->*si_108;
					++si_108;
					if (al_130 == 0x0D || al_130 == 0x00)
						break;
					if (al_130 == 0x22)
						goto l0015_267F;
					if (al_130 == 0x5C)
					{
						cu16 cx_448 = 0x00;
						do
						{
							++cx_448;
							byte al_456 = ds_61->*si_108;
							++si_108;
						} while (al_456 == 0x5C);
						if (al_456 == 0x22)
						{
							dx_120 = (word16) ((bool) (cx_448 >> 0x01 < 0x00) + (dx_120 + (cx_448 >> 0x01)));
							if (((byte) cx_448 & 0x01) == 0x00)
								goto l0015_267F;
							continue;
						}
						else
						{
							dx_120 += cx_448;
							--si_108;
							continue;
						}
					}
					++dx_120;
				}
				goto l0015_26E8;
			}
			if (al_86 == 0x5C)
			{
				cu16 cx_102 = 0x00;
				do
				{
					++cx_102;
					byte al_110 = ds_61->*si_108;
					++si_108;
				} while (al_110 == 0x5C);
				if (al_110 != 0x22)
				{
					dx_120 += cx_102;
					goto l0015_267E;
				}
				dx_120 = (word16) ((bool) (cx_102 >> 0x01 < 0x00) + (dx_120 + (cx_102 >> 0x01)));
				if (((byte) cx_102 & 0x01) != 0x00)
					continue;
				goto l0015_26B8;
			}
			++dx_120;
		}
	}
l0015_26E8:
	ss->*((word32) sp_24 - 4) = es_57;
	Eq_107 ds_152 = ss->*((word32) sp_24 - 4);
	*((word32) ds_152 + 24504) = di_154;
	cui16 di_162 = di_154 + 0x01;
	word16 dx_165 = dx_120 + di_154 + (di_162 << 0x02);
	Eq_4490 sp_171 = sp_24 - 0x02 - SEQ(SLICE(dx_165 + 0x01, byte, 8), (byte) (dx_165 + 0x01) & ~0x01);
	*((word32) ds_152 + 0x00005FBA) = sp_171;
	*((word32) ds_152 + 0x00005FBC) = ss;
	ss->*((word16) sp_171 - 2) = ss;
	Eq_4466 ds_si_181 = *((word32) ds_152 + 24514);
	Eq_4490 es_179 = ss->*((word16) sp_171 - 2);
	ss->*sp_171 = (word16) ds_si_181;
	ss->*((word16) sp_171 + 2) = SLICE(ds_si_181, selector, 16);
	ss->*((word16) sp_171 - 2) = sp_171;
	Eq_4619 di_176 = (word16) sp_171 + (di_162 << 0x02);
	struct Eq_4622 Eq_4490::* bx_186 = (word16) sp_171 + 4;
	struct Eq_4050 * ds_198 = fn0015_29DC()->ptr5F7E;
	byte Eq_4050::* si_199 = &Eq_4050::b0081;
	while (true)
	{
		do
		{
			byte al_203 = ds_198->*si_199;
			++si_199;
		} while (al_203 == 0x20 || al_203 == 0x09);
		if (al_203 == 0x0D || al_203 == 0x00)
			break;
		(ss->*bx_186).w0000 = di_176;
		(ss->*bx_186).w0002 = ss;
		++bx_186;
l0015_274E:
		--si_199;
		while (true)
		{
l0015_274F:
			byte al_228 = ds_198->*si_199;
			++si_199;
			if (al_228 == 0x20 || al_228 == 0x09)
				break;
			if (al_228 == 0x0D || al_228 == 0x00)
			{
l0015_27BE:
				es_179->*di_176 = 0x00;
				goto l0015_27C1;
			}
			if (al_228 == 0x22)
			{
l0015_278B:
				while (true)
				{
					byte al_276 = ds_198->*si_199;
					++si_199;
					if (al_276 == 0x0D || al_276 == 0x00)
						break;
					if (al_276 == 0x22)
						goto l0015_274F;
					if (al_276 == 0x5C)
					{
						cu16 cx_298 = 0x00;
						do
						{
							++cx_298;
							byte al_306 = ds_198->*si_199;
							++si_199;
						} while (al_306 == 0x5C);
						if (al_306 == 0x22)
						{
							uint16 cx_313;
							for (cx_313 = cx_298 >> 0x01; cx_313 != 0x00; --cx_313)
							{
								es_179->*di_176 = 0x5C;
								di_176 = (word16) di_176 + 1;
							}
							if (cx_298 >> 0x01 >= 0x00)
								goto l0015_274F;
							es_179->*di_176 = 0x22;
							di_176 = (word16) di_176 + 1;
							continue;
						}
						else
						{
							for (; cx_298 != 0x00; --cx_298)
							{
								es_179->*di_176 = 0x5C;
								di_176 = (word16) di_176 + 1;
							}
							--si_199;
							continue;
						}
					}
					es_179->*di_176 = al_276;
					di_176 = (word16) di_176 + 1;
				}
				goto l0015_27BE;
			}
			if (al_228 == 0x5C)
			{
				cu16 cx_254 = 0x00;
				do
				{
					++cx_254;
					byte al_262 = ds_198->*si_199;
					++si_199;
				} while (al_262 == 0x5C);
				if (al_262 != 0x22)
				{
					for (; cx_254 != 0x00; --cx_254)
					{
						es_179->*di_176 = 0x5C;
						di_176 = (word16) di_176 + 1;
					}
					goto l0015_274E;
				}
				uint16 cx_269;
				for (cx_269 = cx_254 >> 0x01; cx_269 != 0x00; --cx_269)
				{
					es_179->*di_176 = 0x5C;
					di_176 = (word16) di_176 + 1;
				}
				if (cx_254 >> 0x01 < 0x00)
				{
					es_179->*di_176 = 0x22;
					di_176 = (word16) di_176 + 1;
					continue;
				}
				goto l0015_278B;
			}
			es_179->*di_176 = al_228;
			di_176 = (word16) di_176 + 1;
		}
		es_179->*di_176 = 0x00;
		di_176 = (word16) di_176 + 1;
	}
l0015_27C1:
	struct Eq_4050 * ax_358 = fn0015_29DC();
	(ss->*bx_186).w0000 = 0x00;
	(ss->*bx_186).w0002 = 0x00;
	word16 dx_440;
	ax_358->ptr5FD2();
	return dx_440;
}

// 0015:27D6: Register Eq_4466 fn0015_27D6(Register Eq_107 dx, Register out (ptr16 Eq_4035) dxOut, Register out ptr16 bpOut)
// Called from:
//      fn0015_2300
Eq_4466 fn0015_27D6(Eq_107 dx, struct Eq_4035 & dxOut, ptr16 & bpOut)
{
	GetDOSEnvironment();
	if (ds != 0x00)
		dx.u0 = 0x00;
	word16 di_309 = 0x00;
	word16 cx_254 = ~0x00;
	if (dx != 0x00 && *dx.u0 != 0x00)
	{
		do
		{
			if (cx_254 != 0x00)
			{
				++di_309;
				--cx_254;
				if (dx->*di_309 == 0x00)
					continue;
			}
			++di_309;
		} while (dx->*di_309 != 0x00);
	}
	word16 ax_63 = di_309 + 1;
	word16 di_307;
	Eq_4039 bp_86;
	Eq_4933 dx_91;
	Eq_107 es_92;
	Eq_108 si_93;
	Eq_4466 ax_85 = fn0015_2950(SEQ(SLICE(ax_63, byte, 8), (byte) ax_63 & ~0x01), fp - 2, dx, out dx_91, out bp_86, out si_93, out di_307, out es_92);
	Eq_107 sp_94 = <invalid>;
	ss->*((word32) sp_94 - 4) = dx_91;
	ss->*((word32) sp_94 - 6) = ax_85;
	word16 si_308;
	struct Eq_4961 Eq_4953::* bp_106;
	word16 di_109;
	struct Eq_4035 * dx_111;
	Eq_4933 es_112;
	Eq_4466 ax_105 = fn0015_2950(si_93, bp_86, es_92, out dx_111, out bp_106, out si_308, out di_109, out es_112);
	Eq_107 ds_110 = <invalid>;
	*((word32) ds_110 + 0x00005FBE) = ax_105;
	*((word32) ds_110 + 24512) = dx_111;
	(ss->*bp_106).ptrFFFFFFFA = dx_111;
	Eq_107 sp_114 = <invalid>;
	ss->*((word32) sp_114 - 4) = es_112;
	Eq_4466 bx_128 = ax_105;
	Eq_4933 di_131 = ss->*((word32) sp_114 - 2);
	Eq_4466 es_133 = ss->*sp_114;
	Eq_4466 cx_135 = di_109 - 0x01;
	struct Eq_4997 * ds_si_302 = SEQ(ss->*((word32) sp_114 - 4), 0x00);
	if (di_109 != 0x01)
	{
		do
		{
			word16 ax_140 = ds_si_302->w0000;
			ss->*sp_114 = SLICE(ds_si_302, selector, 16);
			struct Eq_5051 * ds_146 = (ss->*bp_106).ptrFFFFFFF8;
			Eq_4933 si_138 = (word16) ds_si_302;
			bool v22_260 = ax_140 == ds_146->w5F5C;
			Eq_4466 ds_148 = ss->*sp_114;
			if (ax_140 == ds_146->w5F5C)
			{
				ss->*sp_114 = cx_135;
				ss->*((word32) sp_114 - 2) = si_138;
				ss->*((word32) sp_114 - 4) = di_131;
				ss->*((word32) sp_114 - 6) = es_133;
				struct Eq_5051 * es_162 = (ss->*bp_106).ptrFFFFFFF8;
				word16 Eq_5051::* di_163 = &Eq_5051::w5F5C;
				word16 cx_164 = 0x06;
				while (cx_164 != 0x00)
				{
					v22_260 = ds_148->*si_310 == es_162->*di_311;
					si_138 = (word16) si_310 + 2;
					di_163 = di_311 + 1;
					--cx_164;
					si_310 = si_138;
					di_311 = di_163;
					if (ds_148->*si_310 == es_162->*di_311)
						break;
				}
				es_133 = ss->*((word32) sp_114 - 6);
				di_131 = ss->*((word32) sp_114 - 4);
				si_138 = ss->*((word32) sp_114 - 2);
				cx_135 = ss->*sp_114;
				if (!v22_260)
					goto l0015_2867;
			}
			else
			{
l0015_2867:
				struct Eq_4035 * ds_196 = (ss->*bp_106).ptrFFFFFFFA;
				ds_196->*bx_128 = di_131;
				ds_196->*((word32) bx_128 + 2) = es_133;
				bx_128 = (word32) bx_128 + 4;
			}
			Eq_4466 ds_210 = (ss->*bp_106).tFFFFFFFC;
			do
			{
				byte al_214 = ds_210->*si_138;
				es_133->*di_131 = al_214;
				si_138 = (word16) si_138 + 1;
				di_131 = (word16) di_131 + 1;
			} while (al_214 != 0x00);
			--cx_135;
			ds_si_302 = SEQ(ds_210, si_138);
		} while (cx_135 != 0x00);
	}
	struct Eq_4035 * ds_233 = (ss->*bp_106).ptrFFFFFFFA;
	ds_233->*bx_128 = cx_135;
	ds_233->*((word32) bx_128 + 2) = cx_135;
	ptr16 bp_252 = (ss->*bp_106).w0000 - 0x01;
	dxOut = dx_111;
	bpOut = bp_252;
	return cx_135;
}

// 0015:289A: Register (memptr (ptr16 Eq_5183) Eq_5157) fn0015_289A(Stack Eq_107 wArg00, Stack Eq_107 wArg04, Register out ptr16 dxOut, Register out (ptr16 Eq_4091) esOut)
// Called from:
//      fn0015_2300
//      fn0015_23EA
//      fn0015_2950
//      fn0015_55B1
struct Eq_5157 Eq_5183::* fn0015_289A(Eq_107 wArg00, Eq_107 wArg04, ptr16 & dxOut, struct Eq_4091 & esOut)
{
	fn0015_25A8();
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	Eq_107 stackArg4 = <invalid>;
	fn0015_2913(stackArg4);
	struct Eq_5164 * es_147;
	word16 dx_146;
	struct Eq_5157 Eq_5183::* ax_25 = fn0015_28DC(wArg00, out dx_146, out es_147);
	struct Eq_5157 Eq_5183::* ax_34 = ax_25;
	if (ax_25 != &Eq_5183::t0000)
	{
		int16 ax_39 = 0x09;
		if ((ds->*ax_25).b0000 == 77)
			ax_39 = 0x0F;
		struct Eq_5157 Eq_5183::* di_45 = ax_25 + ax_39;
		word16 cx_57 = 0x22;
		di_148 = di_45;
		do
		{
			struct Eq_5157 Eq_5183::* di_148;
			if (cx_57 == 0x00)
				break;
			++di_148;
			--cx_57;
		} while ((ds->*di_148).b0000 == 0x0D);
		(ds->*di_148).bFFFFFFFF = 0x00;
		ax_34 = di_45;
	}
	FatalAppExit(0x00, &&(ds->*(ds->*ax_34).b0000));
	FatalExit();
	ptr16 dx_106;
	struct Eq_4091 * es_107;
	struct Eq_5157 Eq_5183::* ax_105 = fn0015_28DC(wArg04, out dx_106, out es_107);
	dxOut = dx_106;
	esOut = es_107;
	return ax_105;
}

// 0015:28DC: Register (memptr (ptr16 Eq_5171) Eq_5224) fn0015_28DC(Stack Eq_107 wArg04, Register out Eq_107 dxOut, Register out (ptr16 Eq_5171) esOut)
// Called from:
//      fn0015_289A
//      fn0015_2913
struct Eq_5224 Eq_5171::* fn0015_28DC(Eq_107 wArg04, union Eq_107 & dxOut, struct Eq_5171 & esOut)
{
	struct Eq_5224 Eq_5171::* si_27 = &Eq_5171::t63FE;
	while (true)
	{
		Eq_107 ax_31 = (ds->*si_27).t0000;
		struct Eq_5224 Eq_5171::* si_32 = si_27 + 2;
		if (ax_31 == wArg04)
			break;
		si_32 = (word16) ax_31 + 1;
		if (ax_31 == 0x01)
			break;
		struct Eq_5224 Eq_5171::* di_135 = si_32;
		word16 cx_71 = ~0x00;
		while (cx_71 != 0x00)
		{
			++di_135;
			--cx_71;
			if ((ds->*di_135).t0000 != 0x00)
				break;
		}
		si_27 = di_135;
	}
	dxOut = wArg04;
	esOut = ds;
	return si_32;
}

// 0015:2913: void fn0015_2913(Stack Eq_107 wArg04)
// Called from:
//      fn0015_25A8
//      fn0015_289A
void fn0015_2913(Eq_107 wArg04)
{
	if (ds->w61EC != 0x00)
	{
		struct Eq_5183 * es_25;
		word16 dx_124;
		struct Eq_5157 Eq_5183::* ax_23 = fn0015_28DC(wArg04, out dx_124, out es_25);
		if (ax_23 != &Eq_5183::t0000)
		{
			struct Eq_5157 Eq_5183::* di_38 = ax_23;
			word16 cx_42 = ~0x00;
			while (cx_42 != 0x00)
			{
				di_38 = di_125 + 1;
				--cx_42;
				di_125 = di_38;
				if ((es_25->*di_125).b0000 != 0x00)
					break;
			}
			fn0015_55B1();
		}
	}
}

// 0015:2950: Register Eq_108 fn0015_2950(Register Eq_108 ax, Register Eq_4039 bp, Register Eq_107 es, Register out Eq_4472 dxOut, Register out Eq_4039 bpOut, Register out Eq_107 siOut, Register out Eq_107 diOut, Register out Eq_107 esOut)
// Called from:
//      fn0015_262C
//      fn0015_27D6
Eq_108 fn0015_2950(Eq_108 ax, Eq_4039 bp, Eq_107 es, union Eq_4472 & dxOut, union Eq_4039 & bpOut, union Eq_107 & siOut, union Eq_107 & diOut, union Eq_107 & esOut)
{
	word16 v8_20 = ds->w6066;
	ds->w6066 = 0x1000;
	word16 di_31;
	Eq_4472 dx_33;
	word16 si_35;
	Eq_108 ax_28 = fn0015_167A(ax, out dx_33, out si_35, out di_31);
	Eq_107 ds_32 = <invalid>;
	*((word32) ds_32 + 0x00006066) = v8_20;
	if ((dx_33 | ax_28) == 0x00)
	{
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		Eq_107 stackArg4 = <invalid>;
		Eq_4472 dx_55;
		Eq_107 es_56;
		Eq_108 ax_52 = fn0015_289A(es, stackArg4, out dx_55, out es_56);
		dxOut = dx_55;
		bpOut = fp - 2;
		siOut.u0 = <invalid>;
		diOut.u0 = <invalid>;
		esOut = es_56;
		return ax_52;
	}
	else
	{
		dxOut = dx_33;
		bpOut = bp;
		siOut.u0 = <invalid>;
		diOut.u0 = <invalid>;
		esOut = es;
		return ax_28;
	}
}

// 0015:29DC: Register (ptr16 Eq_5319) fn0015_29DC()
// Called from:
//      fn0015_23EA
//      fn0015_262C
struct Eq_5319 * fn0015_29DC()
{
	if (0015->b29EC == 0xB8)
		return 0015->ptr29ED;
	return ss;
}

// 0015:29EC: void __EXPORTEDSTUB()
void __EXPORTEDSTUB()
{
}

// 0015:3D3E: void fn0015_3D3E(Stack Eq_107 ptrArg04, Stack (ptr32 Eq_5006) ptrArg08)
// Called from:
//      fn0045_60E8
void fn0015_3D3E(Eq_107 ptrArg04, union Eq_5006 * ptrArg08)
{
	struct Eq_5329 Eq_5331::* si_105 = (word16) ptrArg08;
	struct Eq_5331 * ds_19 = SLICE(ptrArg08, selector, 16);
	struct Eq_5329 Eq_5331::* di_18 = si_105;
	bool v25_129 = true;
	word16 cx_25 = ~0x00;
	while (cx_25 != 0x00)
	{
		v25_129 = (ds_19->*di_165).t0000 == 0x00;
		di_18 = di_165 + 1;
		--cx_25;
		di_165 = di_18;
		if ((ds_19->*di_165).t0000 != 0x00)
			break;
	}
	struct Eq_5338 Eq_5342::* di_103 = (word16) ptrArg04;
	cu16 cx_36 = ~cx_25;
	struct Eq_5342 * es_57 = SLICE(ptrArg04, selector, 16);
	byte al_48 = (byte) di_103;
	if (!v25_129)
	{
		*ptrArg04 = *ptrArg08;
		si_105 += 2;
		di_103 += 2;
		--cx_36;
	}
	else if ((al_48 & 0x01) != 0x00)
	{
		*ptrArg04 = *ptrArg08;
		++si_105;
		++di_103;
		--cx_36;
	}
	uint16 cx_70 = cx_36 >> 0x01;
	cx_107 = cx_70;
	while (true)
	{
		uint16 cx_107;
		if (cx_107 == 0x00)
			break;
		(es_57->*di_103).t0000 = (ds_19->*si_105).t0000;
		si_105 += 2;
		di_103 += 2;
		--cx_107;
	}
	ui16 cx_74;
	for (cx_74 = cx_107 * 0x02 + (cx_70 < 0x00); cx_74 != 0x00; --cx_74)
	{
		(es_57->*di_103).t0000 = (ds_19->*si_105).t0000;
		++si_105;
		++di_103;
	}
}

// 0015:3DA4: Register word16 fn0015_3DA4(Stack (ptr32 Eq_5006) ptrArg04)
// Called from:
//      fn0015_3EC0
//      fn0045_60E8
word16 fn0015_3DA4(union Eq_5006 * ptrArg04)
{
	struct Eq_5430 * es_57 = SLICE(ptrArg04, selector, 16);
	byte Eq_5430::* di_19 = (word16) ptrArg04;
	bool v19_59 = false;
	word16 cx_15 = ~0x00;
	while (cx_15 != 0x00)
	{
		v19_59 = es_57->*di_91 != 0x00;
		di_19 = di_91 + 1;
		--cx_15;
		di_91 = di_19;
		if (es_57->*di_91 != 0x00)
			break;
	}
	word16 cx_26 = ~cx_15;
	if (!v19_59)
		--cx_26;
	return cx_26;
}

// 0015:3DBE: void fn0015_3DBE(Stack segptr32 ptrArg04, Stack Eq_107 ptrArg08, Stack word16 wArg0C)
// Called from:
//      fn0015_440C
void fn0015_3DBE(segptr32 ptrArg04, Eq_107 ptrArg08, word16 wArg0C)
{
	byte Eq_5463::* di_20 = (word16) ptrArg04;
	struct Eq_5463 * es_46 = SLICE(ptrArg04, selector, 16);
	struct Eq_5465 * ds_70 = SLICE(ptrArg08, selector, 16);
	byte Eq_5465::* si_24 = (word16) ptrArg08;
	word16 cx_22 = wArg0C;
	if (wArg0C != 0x00)
	{
		do
		{
			byte al_26 = ds_70->*si_24;
			++si_24;
			if (al_26 == 0x00)
				break;
			es_46->*di_20 = al_26;
			++di_20;
			--cx_22;
		} while (cx_22 != 0x00);
		for (; cx_22 != 0x00; --cx_22)
		{
			es_46->*di_20 = 0x00;
			++di_20;
		}
	}
}

// 0015:3DE8: Register Eq_5499 fn0015_3DE8(Stack segptr32 ptrArg04, Stack (ptr32 Eq_5006) ptrArg08, Stack Eq_5499 wArg0C)
// Called from:
//      fn0015_3EC0
Eq_5499 fn0015_3DE8(segptr32 ptrArg04, union Eq_5006 * ptrArg08, Eq_5499 wArg0C)
{
	Eq_5499 cx_18 = wArg0C;
	if (wArg0C == 0x00)
		return cx_18;
	struct Eq_5506 Eq_5508::* di_21 = (word16) ptrArg04;
	struct Eq_5508 * es_103 = SLICE(ptrArg04, selector, 16);
	di_29 = di_21;
	do
	{
		struct Eq_5506 Eq_5508::* di_29;
		if (cx_18 == 0x00)
			break;
		di_29 = di_172 + 1;
		--cx_18;
		di_172 = di_29;
	} while ((es_103->*di_172).b0000 == 0x00);
	word16 cx_39 = (word32) wArg0C + -cx_18;
	struct Eq_5506 Eq_5508::* di_174 = di_21;
	struct Eq_5515 * ds_104 = SLICE(ptrArg08, selector, 16);
	struct Eq_5517 Eq_5515::* si_105 = (word16) ptrArg08;
	while (cx_39 != 0x00)
	{
		++si_105;
		++di_174;
		--cx_39;
		if ((ds_104->*si_105).b0000 == (es_103->*di_174).b0000)
			break;
	}
	cu8 al_64 = (ds_104->*si_105).bFFFFFFFF;
	cx_18.u0 = 0x00;
	if (al_64 <= (es_103->*di_174).bFFFFFFFF)
	{
		if (al_64 == (es_103->*di_174).bFFFFFFFF)
			return cx_18;
		cx_18.u0 = ~0x01;
	}
	cx_18 = ~cx_18;
	return cx_18;
}

// 0015:3E28: Register uint16 fn0015_3E28(Stack segptr32 ptrArg04, Register out ptr16 dxOut)
// Called from:
//      fn0015_440C
uint16 fn0015_3E28(segptr32 ptrArg04, ptr16 & dxOut)
{
	struct Eq_5564 * ds_126 = SLICE(ptrArg04, selector, 16);
	byte Eq_5564::* si_127 = (word16) ptrArg04;
	ptr16 dx_124 = 0x00;
	uint16 bx_121 = 0x00;
	do
	{
		do
		{
			cu8 al_27 = ds_126->*si_127;
			++si_127;
		} while (al_27 == 0x20);
		uint16 ax_37 = (uint16) al_27;
	} while (al_27 == 0x09);
	if (al_27 == 0x2D || al_27 == 0x2B)
	{
l0015_3E4C:
		al_27 = ds_126->*si_127;
		++si_127;
		goto l0015_3E4D;
	}
	else
	{
l0015_3E4D:
		if (al_27 <= 0x39)
		{
			cu8 al_52 = al_27 - 0x30;
			uint16 ax_120 = (uint16) al_52;
			if (al_52 >= 0x00)
			{
				ui16 bx_97 = bx_121 << 0x01;
				ptr16 dx_101 = __rcl(dx_124, 0x01, SLICE(cond(bx_97), bool, 1));
				bx_121 = bx_97 * 0x05 + ax_120;
				dx_124 = (ptr16) ((bool) (bx_121 < 0x00) + ((bool) (bx_97 * 0x05 < 0x00) + (__rcl(__rcl(dx_101, 0x01, SLICE(cond(bx_97 << 0x01), bool, 1)), 0x01, SLICE(cond(bx_97 << 0x02), bool, 1)) + dx_101)));
				goto l0015_3E4C;
			}
		}
		uint16 ax_159 = bx_121;
		if ((byte) ax_37 == 0x2D)
		{
			ax_159 = -bx_121;
			dx_124 = -((bool) (ax_159 == 0x00) + dx_124);
		}
		dxOut = dx_124;
		return ax_159;
	}
}

// 0015:3E9E: void fn0015_3E9E()
// Called from:
//      fn0015_214C
void fn0015_3E9E()
{
	FatalAppExit(0x00, (char *) ds + 0x00006544);
}

// 0015:3EC0: void fn0015_3EC0(Stack (ptr32 Eq_5006) dwArg04)
// Called from:
//      fn0015_440C
void fn0015_3EC0(union Eq_5006 * dwArg04)
{
	cui16 wArg06 = SLICE(dwArg04, word16, 16);
	cui16 wArg04 = (word16) dwArg04;
	cui16 ax_17 = ds->w5FBE;
	cui16 dx_18 = ds->w5FC0;
	struct Eq_5667 * ptrLoc08_163 = SEQ(dx_18, ax_17);
	if ((dx_18 | ax_17) != 0x00 && (wArg06 | wArg04) != 0x00)
	{
		Eq_5499 ax_36 = fn0015_3DA4(dwArg04);
		while (true)
		{
			word16 wLoc08_177 = (word16) ptrLoc08_163;
			word16 wLoc06_193 = SLICE(ptrLoc08_163, word16, 16);
			if ((ptrLoc08_163->w0002 | ptrLoc08_163->w0000) == 0x00)
				break;
			if (fn0015_3DA4(SEQ(ptrLoc08_163->w0002, ptrLoc08_163->w0000)) > ax_36 && (Mem68[Mem68[ds:SLICE(ptrLoc08_163, word16, 0) + 0x00:segptr32] + ax_36:byte] == 0x3D && fn0015_3DE8(SEQ(ptrLoc08_163->w0002, ptrLoc08_163->w0000), dwArg04, ax_36) == 0x00))
				return;
			ptrLoc08_163 = SEQ(wLoc06_193, wLoc08_177 + 0x04);
		}
	}
}

// 0015:435C: Register word16 fn0015_435C(Register word16 cx, Register word16 dx, Stack (ptr32 Eq_5728) ptrArg04)
// Called from:
//      fn0045_54AA
word16 fn0015_435C(word16 cx, word16 dx, struct Eq_5728 * ptrArg04)
{
	byte dh_35 = SLICE(dx, byte, 8);
	word16 wArg06 = SLICE(ptrArg04, word16, 16);
	byte cl_45 = (byte) cx;
	byte ch_51 = SLICE(cx, byte, 8);
	if ((0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
		__syscall(33);
	if ((0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
		__syscall(33);
	uint16 ax_40 = (uint16) dh_35;
	uint16 ax_48 = (uint16) cl_45;
	uint16 ax_54 = (uint16) ch_51;
	byte dl_83 = (byte) dx;
	byte dh_92 = SLICE(dx, byte, 8);
	if ((0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
		__syscall(33);
	byte al_75 = (byte) ax_54;
	if (false && al_75 == 0x17)
	{
		dl_83 = (byte) dx;
		dh_92 = SLICE(dx, byte, 8);
	}
	word16 dx_117;
	word16 ax_114 = fn0015_462E(cx - 0x07BC, (uint16) dh_92, (uint16) dl_83, ax_54, ax_48, ax_40, out dx_117);
	if (wArg06 != 0x00)
	{
		ptrArg04->w0002 = dx_117;
		ptrArg04->w0000 = ax_114;
	}
	return ax_114;
}

// 0015:43F0: void fn0015_43F0()
// Called from:
//      fn0015_462E
void fn0015_43F0()
{
	if (ds->w68B4 == 0x00)
	{
		fn0015_440C();
		++ds->w68B4;
	}
}

// 0015:440C: void fn0015_440C()
// Called from:
//      fn0015_43F0
void fn0015_440C()
{
	fn0015_3EC0((char *) ds + 0x000061CA);
	Eq_107 dx_ax_532 = <invalid>;
	cui16 dx_26 = SLICE(dx_ax_532, word16, 16);
	cui16 ax_25 = (word16) dx_ax_532;
	word16 si_17 = 0x00;
	if ((dx_26 | ax_25) != 0x00 && *dx_ax_532 != 0x00)
	{
		fn0015_3DBE(SEQ(ds->w61DE, ds->w61DC), dx_ax_532, 0x03);
		cui16 wLoc08_360 = ax_25 + 0x03;
		if (*SEQ(dx_26, ax_25 + 0x03) == 0x2D)
		{
			si_17 = 0x01;
			wLoc08_360 = ax_25 + 0x04;
		}
		uint16 dx_99;
		ui16 dx_112;
		ds->w61CE = fn0015_52BE(fn0015_3E28(SEQ(dx_26, wLoc08_360), out dx_99), dx_99, 0x0E10, 0x00, out dx_112);
		ds->w61D0 = dx_112;
		Eq_107 ptrLoc08_372 = SEQ(dx_26, wLoc08_360);
		while (true)
		{
			word16 wLoc08_376 = (word16) ptrLoc08_372;
			word16 wLoc06_397 = SLICE(ptrLoc08_372, word16, 16);
			struct Eq_5909 * es_125 = SLICE(ptrLoc08_372, selector, 16);
			if (*ptrLoc08_372 != 0x2B && (*ptrLoc08_372 < 0x30 || *ptrLoc08_372 > 0x39))
				break;
			ptrLoc08_372 = SEQ(wLoc06_397, wLoc08_376 + 0x01);
		}
		Eq_107 ptrLoc08_391 = ptrLoc08_372;
		if (*ptrLoc08_372 == 0x3A)
		{
			uint16 dx_160;
			word16 dx_535;
			fn0015_52BE(fn0015_3E28(wLoc08_376 + 0x01, out dx_160), dx_160, 0x3C, 0x00, out dx_535);
			Eq_107 dx_ax_533 = <invalid>;
			ui32 v26_v25_340 = (word32) dx_ax_533 + SEQ(ds->w61D0, ds->w61CE);
			ds->w61CE = (word16) v26_v25_340;
			ds->w61D0 = SLICE(v26_v25_340, word16, 16);
			Eq_107 ptrLoc08_383 = SEQ(wLoc06_397, wLoc08_376 + 0x01);
			while (true)
			{
				word16 wLoc08_384 = (word16) ptrLoc08_383;
				word16 wLoc06_400 = SLICE(ptrLoc08_383, word16, 16);
				struct Eq_5950 * es_192 = SLICE(ptrLoc08_383, selector, 16);
				if (*ptrLoc08_383 < 0x30 || *ptrLoc08_383 > 0x39)
					break;
				ptrLoc08_383 = SEQ(wLoc06_400, wLoc08_384 + 0x01);
			}
			ptrLoc08_391 = ptrLoc08_383;
			if (*ptrLoc08_383 == 0x3A)
			{
				word16 dx_536;
				fn0015_3E28(wLoc08_384 + 0x01, out dx_536);
				Eq_107 dx_ax_534 = <invalid>;
				ui32 v33_v32_342 = (word32) dx_ax_534 + SEQ(ds->w61D0, ds->w61CE);
				ds->w61CE = (word16) v33_v32_342;
				ds->w61D0 = SLICE(v33_v32_342, word16, 16);
				ptrLoc08_391 = SEQ(wLoc06_400, wLoc08_384 + 0x01);
				while (true)
				{
					word16 wLoc08_392 = (word16) ptrLoc08_391;
					word16 wLoc06_402 = SLICE(ptrLoc08_391, word16, 16);
					if (*ptrLoc08_391 < 0x30 || *ptrLoc08_391 > 0x39)
						break;
					ptrLoc08_391 = SEQ(wLoc06_402, wLoc08_392 + 0x01);
				}
			}
		}
		if (si_17 != 0x00)
		{
			uint16 v27_261 = -ds->w61CE;
			ds->w61CE = v27_261;
			ds->w61D0 = (ui16) ((bool) (v27_261 == 0x00) + ds->w61D0);
			ds->w61D0 = -ds->w61D0;
		}
		int16 ax_279 = (int16) *ptrLoc08_391;
		ds->w61D2 = ax_279;
		if (ax_279 != 0x00)
			fn0015_3DBE(SEQ(ds->w61E2, ds->t61E0), ptrLoc08_391, 0x03);
		else
			*ds->t61E0 = 0x00;
	}
}

// 0015:455A: Register word16 fn0015_455A(Stack (ptr32 Eq_6047) ptrArg04)
// Called from:
//      fn0015_462E
word16 fn0015_455A(struct Eq_6047 * ptrArg04)
{
	word16 ax_129;
	if (ptrArg04->w000A >= 0x43 && (ptrArg04->w0008 >= 0x03 && ptrArg04->w0008 <= 0x09))
	{
		if (ptrArg04->w0008 <= 0x03 || ptrArg04->w0008 >= 0x09)
		{
			word16 ax_46;
			int16 si_33 = ptrArg04->w000A;
			if (si_33 > 0x56 && ptrArg04->w0008 == 0x03)
				ax_46 = ds->a61B0[ptrArg04->w0008] + 0x07;
			else
				ax_46 = ds->a61B2[ptrArg04->w0008];
			word16 wLoc06_157 = ax_46;
			if ((si_33 & 0x03) == 0x00)
				wLoc06_157 = ax_46 + 0x01;
			int32 dx_ax_92 = (int32) ((word16) ((si_33 - 0x46) *s 0x016D) + (si_33 - 0x01 >> 0x02) + wLoc06_157);
			uint16 ax_93 = (word16) dx_ax_92;
			ci16 ax_113 = wLoc06_157 - fn0015_52F0(SEQ(SLICE(dx_ax_92, word16, 16) - (ax_93 < 0x0D), ax_93 - 0x0D), 0x07);
			if (ptrArg04->w0008 == 0x03)
			{
				if (ax_113 >= ptrArg04->w000E && (ax_113 != ptrArg04->w000E || ptrArg04->w0004 < 0x02))
					goto l0015_4623;
			}
			else if (ptrArg04->w000E >= ax_113 && (ptrArg04->w000E != ax_113 || ptrArg04->w0004 >= 0x01))
				goto l0015_4623;
		}
		ax_129 = 0x01;
		return ax_129;
	}
	else
	{
l0015_4623:
		ax_129 = 0x00;
		return ax_129;
	}
}

// 0015:462E: Register cup16 fn0015_462E(Stack int16 wArg04, Stack Eq_5788 wArg06, Stack uint16 wArg08, Stack uint16 wArg0A, Stack uint16 wArg0C, Stack uint16 wArg0E, Register out ptr16 dxOut)
// Called from:
//      fn0015_435C
cup16 fn0015_462E(int16 wArg04, Eq_5788 wArg06, uint16 wArg08, uint16 wArg0A, uint16 wArg0C, uint16 wArg0E, ptr16 & dxOut)
{
	uint16 di_23 = ds->a61AE[wArg06];
	if ((wArg04 & 0x03) == 0x00 && wArg06 > 0x02)
		++di_23;
	fn0015_43F0();
	int32 bx_cx_240 = wArg04 *s 0x016D + ((wArg04 + 0x03 >> 0x02) + wArg08) + SEQ(SLICE((int32) di_23, word16, 16), di_23);
	cup16 cx_95 = (word16) bx_cx_240;
	word16 dx_317;
	fn0015_52BE(cx_95 + 0x0E44, (bool) (cx_95 < 0x0E44) + SLICE(bx_cx_240, word16, 16), 0x18, 0x00, out dx_317);
	Eq_107 dx_ax_313 = <invalid>;
	int32 bx_cx_243 = (word32) dx_ax_313 + (int32) wArg0A;
	word16 dx_318;
	fn0015_52BE((word16) bx_cx_243, SLICE(bx_cx_243, word16, 16), 0x3C, 0x00, out dx_318);
	Eq_107 dx_ax_314 = <invalid>;
	int32 bx_cx_246 = (word32) dx_ax_314 + (int32) wArg0C;
	word16 dx_319;
	fn0015_52BE((word16) bx_cx_246, SLICE(bx_cx_246, word16, 16), 0x3C, 0x00, out dx_319);
	Eq_107 dx_ax_315 = <invalid>;
	int32 bx_cx_251 = (word32) dx_ax_315 + (int32) wArg0E + SEQ(ds->w61D0, ds->w61CE);
	cup16 cx_173 = (word16) bx_cx_251;
	ptr16 bx_176 = SLICE(bx_cx_251, word16, 16);
	cup16 wLoc1A_280 = cx_173;
	ptr16 wLoc18_281 = bx_176;
	if (ds->w61D2 != 0x00 && fn0015_455A(fp - 22) != 0x00)
	{
		wLoc1A_280 = cx_173 - 0x0E10;
		wLoc18_281 = bx_176 - (cx_173 < 0x0E10);
	}
	dxOut = wLoc18_281;
	return wLoc1A_280;
}

// 0015:4D0C: void fn0015_4D0C(Stack word16 wArg04)
// Called from:
//      fn0045_54AA
void fn0015_4D0C(word16 wArg04)
{
	ds->w61E8 = wArg04;
	ds->w61EA = 0x00;
}

// 0015:52BE: Register word16 fn0015_52BE(Stack uint16 wArg04, Stack uint16 wArg06, Stack uint16 wArg08, Stack Eq_107 wArg0A, Register out ptr16 dxOut)
// Called from:
//      fn0015_1902
//      fn0015_440C
//      fn0015_462E
word16 fn0015_52BE(uint16 wArg04, uint16 wArg06, uint16 wArg08, Eq_107 wArg0A, ptr16 & dxOut)
{
	if ((wArg0A | wArg06) != 0x00)
	{
		uint32 dx_ax_27 = wArg08 * wArg04;
		dxOut = SLICE(dx_ax_27, word16, 16) + (word16) (wArg08 * wArg06 + wArg0A * wArg04);
		return (word16) dx_ax_27;
	}
	else
	{
		uint32 dx_ax_36 = wArg08 * wArg04;
		dxOut = SLICE(dx_ax_36, word16, 16);
		return (word16) dx_ax_36;
	}
}

// 0015:52F0: Register uint16 fn0015_52F0(Stack ui32 dwArg04, Stack ui32 dwArg08)
// Called from:
//      fn0015_455A
uint16 fn0015_52F0(ui32 dwArg04, ui32 dwArg08)
{
	ci16 wArg06 = SLICE(dwArg04, word16, 16);
	word16 wArg04 = (word16) dwArg04;
	Eq_6306 wArg0A = SLICE(dwArg08, word16, 16);
	word16 wArg08 = (word16) dwArg08;
	ci16 di_122 = 0x00;
	ui32 dwArg04_251 = dwArg04;
	if (wArg06 < 0x00)
	{
		uint16 dx_24 = -wArg04;
		di_122 = 0x01;
		dwArg04_251 = SEQ(-wArg06 - (dx_24 == 0x00), dx_24);
	}
	Eq_108 wArg04_190 = (word16) dwArg04_251;
	uint16 wArg06_188 = SLICE(dwArg04_251, word16, 16);
	Eq_6306 ax_34 = wArg0A;
	ui32 dwArg08_248 = dwArg08;
	if (wArg0A < 0x00)
	{
		uint16 dx_40 = -wArg08;
		ax_34 = -wArg0A - (dx_40 == 0x00);
		dwArg08_248 = SEQ(ax_34, dx_40);
	}
	uint16 ax_113;
	uint16 wArg0A_192 = SLICE(dwArg08_248, word16, 16);
	Eq_108 wArg08_186 = (word16) dwArg08_248;
	if (ax_34 == 0x00)
	{
		ax_113 = (uint16) (SEQ((uint16) ((uint32) wArg06_188 % wArg08_186), wArg04_190) % wArg08_186);
		if (di_122 < 0x01)
			return ax_113;
		goto l0015_5383;
	}
	Eq_6306 bx_51 = ax_34;
	Eq_108 cx_55 = wArg08_186;
	uint16 dx_56 = wArg06_188;
	Eq_108 ax_57 = wArg04_190;
	do
	{
		Eq_6306 bx_59 = bx_51 >> 0x01;
		dx_56 >>= 0x01;
		cx_55 = __rcr(cx_55, 0x01, SLICE(cond(bx_59), bool, 1));
		ax_57 = __rcr(ax_57, 0x01, SLICE(cond(dx_56), bool, 1));
		bx_51 = bx_59;
	} while (bx_59 != 0x00);
	word32 dx_ax_170;
	uint16 ax_78 = (uint16) (SEQ(dx_56, ax_57) /u cx_55);
	uint32 dx_ax_88 = wArg08_186 * ax_78;
	Eq_108 ax_96 = (word16) dx_ax_88;
	uint16 dx_90 = SLICE(dx_ax_88, word16, 16) + (word16) (wArg0A_192 * ax_78);
	if (dx_90 < 0x00 || dx_90 > wArg06_188)
	{
l0015_5374:
		dx_ax_170 = SEQ(dx_90, ax_96) - dwArg08_248;
		goto l0015_537A;
	}
	else
	{
		dx_ax_170 = SEQ(dx_90, ax_96);
		if (dx_90 >= wArg06_188)
		{
			dx_ax_170 = SEQ(dx_90, ax_96);
			if (ax_96 > wArg04_190)
				goto l0015_5374;
		}
l0015_537A:
		ax_113 = (word16) (dx_ax_170 - dwArg04_251);
		if (di_122 >= 0x01)
			return ax_113;
l0015_5383:
		ax_113 = -ax_113;
		return ax_113;
	}
}

// 0015:5390: Register uint16 fn0015_5390(Stack Eq_108 wArg04, Stack Eq_107 wArg06, Stack Eq_108 wArg08, Stack Eq_107 wArg0A)
// Called from:
//      fn0015_01B0
uint16 fn0015_5390(Eq_108 wArg04, Eq_107 wArg06, Eq_108 wArg08, Eq_107 wArg0A)
{
	uint16 ax_130;
	if (wArg0A == 0x00)
		ax_130 = (uint16) (SEQ((uint16) ((uint32) wArg06 % wArg08), wArg04) /u wArg08);
	else
	{
		Eq_107 cx_20 = wArg0A;
		Eq_108 bx_21 = wArg08;
		Eq_107 dx_22 = wArg06;
		Eq_108 ax_23 = wArg04;
		do
		{
			Eq_107 cx_25 = cx_20 >> 0x01;
			dx_22 >>= 0x01;
			bx_21 = __rcr(bx_21, 0x01, SLICE(cond(cx_25), bool, 1));
			ax_23 = __rcr(ax_23, 0x01, SLICE(cond(dx_22), bool, 1));
			cx_20 = cx_25;
		} while (cx_25 != 0x00);
		uint16 ax_44 = (uint16) (SEQ(dx_22, ax_23) /u bx_21);
		uint32 dx_ax_54 = ax_44 * wArg08;
		uint16 si_45 = ax_44;
		Eq_108 ax_62 = (word16) dx_ax_54;
		Eq_107 dx_56 = SLICE(dx_ax_54, word16, 16) + (word16) (wArg0A * ax_44);
		if (dx_56 < 0x00 || (dx_56 > wArg06 || dx_56 >= wArg06 && ax_62 > wArg04))
			si_45 = ax_44 - 0x01;
		ax_130 = si_45;
	}
	return ax_130;
}

// 0015:55AC: void fn0015_55AC()
// Called from:
//      fn0015_2300
//      fn0015_24DB
void fn0015_55AC()
{
}

// 0015:55B1: void fn0015_55B1()
// Called from:
//      fn0015_2913
void fn0015_55B1()
{
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	Eq_107 stackArg0 = <invalid>;
	Eq_107 stackArg4 = <invalid>;
	word16 dx_12;
	struct Eq_6457 * es_13;
	fn0015_289A(stackArg0, stackArg4, out dx_12, out es_13);
}

