// OUTPOST_0045.c
// Generated by decompiling OUTPOST.EXE
// using Reko decompiler version 0.9.2.3.

#include "OUTPOST_0045.h"

// 0045:0000: Register word16 fn0045_0000(Stack Eq_107 ptrArg04, Register out (ptr16 Eq_6464) dxOut)
// Called from:
//      fn0045_54AA
word16 fn0045_0000(Eq_107 ptrArg04, struct Eq_6464 & dxOut)
{
	*ptrArg04 = 1322;
	((word32) ptrArg04 + 2)->u0 = 0x45;
	((word32) ptrArg04 + 4)->u0 = 0x00;
	*((word32) ptrArg04 + 8) = 0x00;
	*ptrArg04 = 1310;
	((word32) ptrArg04 + 2)->u0 = 0x45;
	dxOut = SLICE(ptrArg04, selector, 16);
	return (word16) (uint32) (word16) ptrArg04;
}

// 0045:54AA: Register word16 fn0045_54AA(Register word16 cx, Register word16 dx, Stack word16 wArg04, Stack (ptr32 Eq_5006) dwArg06, Stack word16 wArg0A, Stack word16 wArg0C)
// Called from:
//      fn0015_23BE
word16 fn0045_54AA(word16 cx, word16 dx, word16 wArg04, union Eq_5006 * dwArg06, word16 wArg0A, word16 wArg0C)
{
	if (wArg0A != 0x00)
		return 0x00;
	int32 dx_ax_524;
	fn0015_4D0C(fn0015_435C(cx, dx, null));
	fn0015_1FEA();
	Eq_107 ds_56 = <invalid>;
	word16 dx_59;
	word16 si_527;
	word16 di_528;
	*((word32) ds_56 + 928) = fn0015_1902(0x00, 0x32, 0x00, 0x12, out dx_59, out si_527, out di_528);
	*((word32) ds_56 + 930) = dx_59;
	Eq_107 ds_75 = <invalid>;
	word16 dx_78;
	word16 si_529;
	word16 di_530;
	*((word32) ds_75 + 668) = fn0015_1902(0x00, 100, 0x00, 0x0C, out dx_78, out si_529, out di_530);
	*((word32) ds_75 + 670) = dx_78;
	Eq_107 ds_94 = <invalid>;
	word16 dx_97;
	word16 si_531;
	word16 di_532;
	*((word32) ds_94 + 20408) = fn0015_1902(0x00, 100, 0x00, 0x10, out dx_97, out si_531, out di_532);
	*((word32) ds_94 + 20410) = dx_97;
	Eq_107 ds_113 = <invalid>;
	word16 dx_116;
	word16 si_533;
	word16 di_534;
	*((word32) ds_113 + 26786) = fn0015_1902(0x00, 100, 0x00, 0x0E, out dx_116, out si_533, out di_534);
	*((word32) ds_113 + 26788) = dx_116;
	Eq_107 ds_132 = <invalid>;
	word16 dx_135;
	word16 si_535;
	word16 di_536;
	*((word32) ds_132 + 0x00005744) = fn0015_1902(0x00, 500, 0x00, 66, out dx_135, out si_535, out di_536);
	*((word32) ds_132 + 22342) = dx_135;
	Eq_107 ds_151 = <invalid>;
	word16 dx_154;
	word16 si_537;
	word16 di_538;
	*((word32) ds_151 + 22376) = fn0015_1902(0x00, 0x32, 0x00, 0x06, out dx_154, out si_537, out di_538);
	*((word32) ds_151 + 22378) = dx_154;
	*((word32) ds_151 + 908) = wArg0C;
	*((word32) ds_151 + 910) = wArg0A;
	*((word32) ds_151 + 912) = wArg04;
	Eq_107 ds_174 = <invalid>;
	word16 dx_178;
	*((word32) ds_174 + 914) = fn0045_60E8(dwArg06, out dx_178);
	*((word32) ds_174 + 916) = dx_178;
	Eq_107 dx_ax_523 = <invalid>;
	word16 cx_191 = fn0015_179C(0x0C);
	Eq_107 ds_193 = <invalid>;
	if ((SLICE(dx_ax_523, word16, 16) | (word16) dx_ax_523) != 0x00)
	{
		int16 dx_217;
		dx_ax_524 = SEQ(dx_217, (word16) (uint32) fn0045_0000(dx_ax_523, out dx_217));
	}
	else
		dx_ax_524 = 0x00;
	word16 dx_256;
	mp16 sp_238 = fp - 0x1A;
	word16 dx_231 = SLICE(dx_ax_524, word16, 16);
	Eq_107 ax_225 = (word16) dx_ax_524;
	dx_256 = dx_231;
	if (*((word32) ds_193 + 914) != 0x00)
	{
		struct Eq_6672 * es_bx_247 = ds_193->*ax_225;
		es_bx_247->ptr0004();
	}
	struct Eq_6662 Eq_6665::* sp_266 = sp_238 - 2;
	(ss->*sp_266).w0000 = dx_231;
	(ss->*sp_266).tFFFFFFFE = ax_225;
	struct Eq_6672 * es_bx_273 = ds_193->*ax_225;
	word16 dx_283;
	word16 cx_286;
	struct Eq_6678 Eq_6665::* sp_281;
	es_bx_273->ptr0008();
	word16 ax_288 = fn0045_9498();
	Eq_107 ax_307 = ax_225;
	if (dx_ax_524 != 0x00)
	{
		(ss->*sp_281).wFFFFFFFE = 0x01;
		(ss->*sp_281).wFFFFFFFC = dx_231;
		(ss->*sp_281).tFFFFFFFA = ax_225;
		word32 eax_311;
		word16 bx_313;
		es_bx_273->ptr0000();
		ax_307 = (word16) eax_311;
	}
	union Eq_108 Eq_6665::* sp_321 = sp_281 - 4;
	ss->*sp_321 = *((word32) ds_193 + 928);
	Eq_107 ax_326 = fn0015_1B68(ax_307, ss->*sp_321);
	Eq_107 ds_329 = <invalid>;
	ss->*sp_321 = *((word32) ds_329 + 668);
	Eq_107 ax_342 = fn0015_1B68(ax_326, ss->*sp_321);
	Eq_107 ds_345 = <invalid>;
	ss->*sp_321 = *((word32) ds_345 + 20408);
	Eq_107 ax_358 = fn0015_1B68(ax_342, ss->*sp_321);
	Eq_107 ds_361 = <invalid>;
	ss->*sp_321 = *((word32) ds_361 + 26786);
	Eq_107 ax_374 = fn0015_1B68(ax_358, ss->*sp_321);
	Eq_107 ds_377 = <invalid>;
	ss->*sp_321 = *((word32) ds_377 + 0x00005744);
	fn0015_1B68(ax_374, ss->*sp_321);
	return ax_288;
}

// 0045:60E8: Register cui16 fn0045_60E8(Stack (ptr32 Eq_5006) dwArg04, Register out Eq_6620 dxOut)
// Called from:
//      fn0045_54AA
cui16 fn0045_60E8(union Eq_5006 * dwArg04, union Eq_6620 & dxOut)
{
	if (dwArg04 != null)
	{
		fn0015_179C((word16) fn0015_3DA4(dwArg04) + 1);
		Eq_107 dx_ax_124 = <invalid>;
		Eq_6620 dx_35 = SLICE(dx_ax_124, word16, 16);
		cui16 ax_30 = (word16) dx_ax_124;
		if ((dx_35 | ax_30) != 0x00)
		{
			fn0015_3D3E(dx_ax_124, dwArg04);
			dxOut = dx_35;
			return ax_30;
		}
	}
	dxOut.u0 = 0x00;
	return 0x00;
}

// 0045:9498: Register word16 fn0045_9498()
// Called from:
//      fn0045_54AA
word16 fn0045_9498()
{
	while (true)
	{
		GetMessage(fp - 22, 0x00, 0x00, 0x00);
		if (true)
			break;
		word16 ax_35 = ds->ptr5BC8->w0008;
		if (ax_35 != 0x00)
		{
			IsDialogMessage(ax_35, fp - 22);
			if (fp != 22)
				continue;
		}
		if (ds->w0398 != 0x00)
		{
			TranslateAccelerator(ds->w0396, ds->w0398, fp - 22);
			if (fp != 22)
				continue;
		}
		TranslateMessage(fp - 22);
		DispatchMessage(fp - 22);
	}
	return wLoc12;
}

