// OUTPOST.globals.c
// Generated by decompiling OUTPOST.EXE
// using Reko decompiler version 0.9.2.3.

#include "OUTPOST.h"

struct Eq_2904 * g_ptr0000;
struct Eq_2 * g_ptr0150;
<anonymous> g_t151F7E;
char g_b38DD940;

